### ISSUE TITLE
DawnAPI incompatibility [Fabric]

### ISSUE THREAD

**Issue by TheSpiderDungeon** [devs-immortal/The-Aether#104]
Spent an hour troubleshooting. Game worked fine enabling 5 mods at a time, crashed on the latest 5. Disabled one at a time until I disabled DawnAPI, and it worked.

Not sure what part of the API causes it, but I have a crash log here if it helps: https://pastebin.com/zxGWWWq0

**Comment by Jack-Papel** [comment]
Fixed in the latest version of DawnAPI
