### ISSUE TITLE
Aether portals can cause nether portal effect to appear on screen.

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#107]
If you enter an aether portal, then leave it before you are teleported, the aether portal swirl screen effect will be replaced with a nether portal swirl screen effect.

**Comment by Jack-Papel** [comment]
Update: The effect also occurs when remaining in a portal after teleporting

**Comment by kyrptonaught** [comment]
This is actually an issue with CustomPortalApi, the portal api the aether is using for its portals.

CustomPortalApi just displays the vanilla nether swirl, and then tints it according to the tint of the portal you are standing in. If you step out of a portal, it no longer knows what type of portal you are in and this doesn't tint.(this also seems to sometimes occur when standing in once for too long) The fix would be just caching the last stepped in portal and clearing it once the swirl affect disappears. I'll get around to this eventually.

**Comment by kyrptonaught** [comment]
This has been fixed in beta28 of customportalapi btw.

**Comment by Jack-Papel** [comment]
That's great to hear. If beta28 is stable we should update to it.
