### ISSUE TITLE
Stacked aerogel slabs don't display correctly when placed next to regular aerogel slabs

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#113]
https://user-images.githubusercontent.com/64770632/107869428-bea03780-6e42-11eb-9322-29185626bd6b.mp4

**Comment by Jack-Papel** [comment]
Fixed by https://github.com/devs-immortal/The-Aether/commit/7f06c613f9f8a9df88fd1e8ba0b3e88f85cfbe33

**Comment by MBatt1** [comment]
non-full block aerogel is being removed, as such this is no longer an issue
