### ISSUE TITLE
Aerogel and Aerogel slabs don't display particles that are behind them

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#115]
Unlike glass, Aerogel blocks and slabs seem to not display particles behind them. See attached:
https://user-images.githubusercontent.com/64770632/107869591-c2cd5480-6e44-11eb-93b0-2ef3ab91c6c9.mp4

**Comment by Hephaestus-Dev** [comment]
This is a limitation of translucent blocks. You'll notice the same thing with stained glass. Fabulous graphics settings should fix it.

**Comment by Jack-Papel** [comment]
Thanks for letting me know
