### ISSUE TITLE
Walking into Golden Aerocloud instantly kills you if it's on the ground

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#116]
In survival mode, walking into a Golden Aerocloud instantly kills you. In creative mode it constantly creates landing particles beneath you.

**Comment by Jack-Papel** [comment]
In the latest update, in creative mode it no longer creates particles, but the survival mode issue still persists.

**Comment by MBatt1** [comment]
In the current dev build, Aerclouds atop or 1 block above the ground no longer shoot you downward, but the physics are still a bit wonky

**Comment by Jack-Papel** [comment]
👍

**Comment by Jack-Papel** [comment]
Using the latest dev build. When golden aercloud is above air, it can still instantly kill you, and creates particles in creative.

https://user-images.githubusercontent.com/64770632/114134604-dfbe5b00-98bc-11eb-9c07-ced130629c20.mp4

**Comment by kalucky0** [comment]
Fixed in #166
