### ISSUE TITLE
Weird elytra movement when flying into blue aerocloud

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#118]
Regularly hitting the blue aerocloud works fine, but using a rocket to boost into it causes weird movement. See attached: 

https://user-images.githubusercontent.com/64770632/107871002-97516680-6e52-11eb-807a-3e7bce1cf279.mp4

**Comment by CDAGaming** [comment]
Nerfed in 1.17 atm, will consider it fixed as its on par with how Aerclouds acted in older versions.
