### ISSUE TITLE
crash with string "main"

### ISSUE THREAD

**Issue by TheTagRapper** [devs-immortal/The-Aether#120]
When launching fabric i get this crash error
```

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'the_aether'!
Exit Code: -1
```
Heres the pastebin of the entire log

https://pastebin.com/Y7PxsvTn

**Comment by Jack-Papel** [comment]
You need geckolib. Here's the install page
https://www.curseforge.com/minecraft/mc-mods/geckolib-fabric
