### ISSUE TITLE
Unable to build. Gradlew error.

### ISSUE THREAD

**Issue by RDKRACZ** [devs-immortal/The-Aether#123]
`./gradlew build`
`Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

**Comment by SweepSwap** [comment]
try redownloading the repo, also make sure you have jdk

**Comment by nailuj29gaming** [comment]
Don't redownload, just `git fetch upstream` of you forked it, or `git fetch origin` if it's just a clone directly from this repo

**Comment by MBatt1** [comment]
was this resolved?

**Comment by CDAGaming** [comment]
Closing, as assumed resolved
