### ISSUE TITLE
Crash Without Geckolib Mod

### ISSUE THREAD

**Issue by BlunderG** [devs-immortal/The-Aether#125]
When your mod were installed, the game would not open and I was getting crashes. When I examined the crash reports, I saw the phrase **at software.bernie.geckolib3.GeckoLib.initialize(GeckoLib.java:28)** and I downloaded the Geckolib mod and tried it again. It worked. 

Your mod crashes without the Geckolib mod. Why that thing happened to me? And if your mod needs this mod, why didn't you specify it?

 It is recommended that you review it so that other people do not experience this problem. Have a nice day :)

[crash-2021-02-26_11.02.15-client.txt](https://github.com/devs-immortal/The-Aether/files/6048314/crash-2021-02-26_11.02.15-client.txt)

**Comment by Hephaestus-Dev** [comment]
I have [a pull request](https://github.com/devs-immortal/The-Aether/pull/124) that fixed this issue. @kalucky0 let this be a formal reminder to merge that :^)

**Comment by kalucky0** [comment]
Fixed in #124 . It will now show the user why the game is crashing.
