### ISSUE TITLE
Texture Bugs

### ISSUE THREAD

**Issue by BlunderG** [devs-immortal/The-Aether#126]
Some textures cause errors. My mods:

aether-1.16.4-beta
better-end-0.9.1-pre
better-nether-5.0.7
fabric-api-0.30.3+1.16
geckolib-fabric-1.16.5-3.0.20
hydrogen-fabric-mc1.16.5-0.2
krypton-0.1.2
lithium-fabric-mc1.16.5-0.6.3
Loadio-1.0.0
modmenu-1.16.7
notenoughcrashes-3.1.5-fabric
overworld-two-1.0.4
smoothboot-fabric-1.16.4-1.4.0
sodium-extra-0.1.0
sodium-fabric-mc1.16.3-0.1.0
starlight-fabric-0.0.3

Bugs look like that:

![maxresdefault](https://user-images.githubusercontent.com/79225884/109278306-6f3a0e00-7829-11eb-8dd7-462ecef230fe.jpg)

**Comment by kalucky0** [comment]
Can you be more specific? There are many textures that are not yet implemented.

**Comment by nonetrix** [comment]
Also when you wear some of the armor without textures it will crash the game when going into F5 or when ever you load the 3th person model, this could be very problematic for multiplayer I imagine, would be best to give them a placeholder texture and model.

**Comment by nonetrix** [comment]
You also might be able to do something like this mod https://www.curseforge.com/minecraft/mc-mods/surrogate

**Comment by MBatt1** [comment]
Is this  still relevant? besides armor, unimplemented mobs and very few other items textures should be almost all done
