### ISSUE TITLE
Incompatible with Roughly Enough Items

### ISSUE THREAD

**Issue by filipesn** [devs-immortal/The-Aether#137]
When using the latest verion of Aether and REI, the REI menu that shows all the items doesn't load. The mod still apears as loaded and no i havent disabled it with crtl + o or some other binding.

**Comment by Dragon-Seeker** [comment]
The best solution that I have found is by going to roughly enough items and hitting the reload plugins button in mod menu. I believe its cause by whatever aether bar is on the left of the screen when loading a world.

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/121788080-0a17e780-cb90-11eb-9be6-f6b35b1e3c49.png)
This appears to be resolved. Would recommend a re-test here.
