### ISSUE TITLE
Lone floating blocks

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#146]
In the aether, lone floating blocks will generate. See attached: 

https://drive.google.com/file/d/11dNfIK0xsonRMqnX1ID8QZsBd69WtkrS/view?usp=sharing

**Comment by Haven-King** [comment]
There's not a whole lot that can be done about this. That's just an artifact of Minecraft's worldgen. They do seem relatively common in that video though.

**Comment by Jack-Papel** [comment]
I figured. Flying around at fast speeds may make them seem more prevalent than they really are, also.
