### ISSUE TITLE
Aether Grass Block Item top face displayed incorrectly

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#147]
Ah, the good old grass top texture issue. Grayscale grass texture on top of a dropped aether grass block item. See attached:

![2021-03-26_20 30 53](https://user-images.githubusercontent.com/64770632/112708905-4af63f00-8e72-11eb-866a-e6c27f1d859a.png)

**Comment by Jack-Papel** [comment]
The grass top texture is also gray when held in the player's hand. Seems to smoothly change from gray to colored based on the player's pitch rotation.

**Comment by Jack-Papel** [comment]
(To be added to https://github.com/devs-immortal/The-Aether/milestone/1 )

**Comment by CDAGaming** [comment]
Re-test is warranted here, unable to reproduce this in the latest version of 1.16.5 nor 1.17

**Comment by CDAGaming** [comment]
Assuming resolved in 1.17
