### ISSUE TITLE
Blueberry bushes cannot be planted

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#148]
This probably just hasn't been implemented yet. See attached:

https://user-images.githubusercontent.com/64770632/112709259-0029f680-8e75-11eb-9ddd-0ea834fc741b.mp4

**Comment by CDAGaming** [comment]
In code, this seems intended. Requesting secondary lookthrough on this.

**Comment by Jack-Papel** [comment]
I've been told by 24Chrome (from the discord) that blueberry bushes are supposed to act like sweet berry bushes

**Comment by Dragonoidzero** [comment]
Well, we will need to ask whoever implemented them to see... _looks at commits_ fuck it was me. Um. I'll look into it.

**Comment by Jack-Papel** [comment]
Resolved according to #154
