### ISSUE TITLE
Gravitite block levitation weirdness

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#157]
https://user-images.githubusercontent.com/53229958/112777846-cb4ea880-9008-11eb-811c-35fd66ebb5d0.mp4

See attached video.

**Comment by Dragonoidzero** [comment]
I... did... did they just bounce midair?

**Comment by Jack-Papel** [comment]
The gravitite ore blocks used to have this issue too, but they no longer do.

**Comment by CDAGaming** [comment]
Yea, I've seen this before on the ores before they got fixed

**Comment by MBatt1** [comment]
Some strange velocity code based on their life value which I fixed, it now is just a flat acceleration, and they disappear when they go high enough up, if a player is riding it drops itself
