### ISSUE TITLE
Server datapack load fail: gravitite_gemstone does not exist

### ISSUE THREAD

**Issue by HerrahStrings** [devs-immortal/The-Aether#164]
On 0a45b02ea68bbe9436dca03e87bc48d26ce5b065, MC 1.16.5 with fabric 0.11.3, server crashes on startup ([latest.log](https://github.com/devs-immortal/The-Aether/files/6275572/latest.log)) with the following (minimal) mods:
![image](https://user-images.githubusercontent.com/55819817/113958011-ab6a8080-9863-11eb-80de-3f13ad8c4f0c.png)

`Failed to load datapacks, can't proceed with server load.`
`Item: the_aether:gravitite_gemstone does not exist`

Also occurred on 6eb670f57d2caa1332892207a3a57c17f2b1f787 with regards to `ambrosium_shard`

**Comment by HerrahStrings** [comment]
This issue appears to persist in LAN (though it's unclear if the issue is unrelated) - on connect, Connection Lost: `Registry remapping failed: Received ID map for minecraft:block contains IDs unknown to the receiver! - the_aether:block_of_gravitite`

**Comment by linuxxxer** [comment]
I've got the same issue, with minecraft version 1.16.5. I am unable to start the server, the same error appears with beta 1.0.2.

**Comment by MBatt1** [comment]
resolved in b1.0.3
