### ISSUE TITLE
If you don't care about/have time for #168.

### ISSUE THREAD

**Issue by RDKRACZ** [devs-immortal/The-Aether#169]
Temporary workaround till #168 is (hopefully) resolved.
Tabs which should be merged together. 
Tools with Weapons (they are tools too so why isn't this together at first place.
![image](https://user-images.githubusercontent.com/43277609/114191283-8a318f00-994c-11eb-9a77-c0c29d0d048b.png)
![image](https://user-images.githubusercontent.com/43277609/114191310-90277000-994c-11eb-98fb-f6a9064dcd2e.png)

Armor with Accessories, under the name Wearables
![image](https://user-images.githubusercontent.com/43277609/114191402-a8978a80-994c-11eb-8704-c05a471588db.png)
![image](https://user-images.githubusercontent.com/43277609/114191552-d5e43880-994c-11eb-9f6a-8c9c44dd2c24.png)

There is also: Misc, Foods, Materials, Blocks.
Maybe Foods + Misc?

**Comment by nailuj29gaming** [comment]
I'll work on this if none of the devs hate it
