### ISSUE TITLE
[Server] Dedicated server crashes upon loading a gravitite ore entity (item)

### ISSUE THREAD

**Issue by Simeonlps** [devs-immortal/The-Aether#185]
Judging from logs [here](https://del.dog/histyrecyw.txt) it seems that upon ticking the block shortly after mining it, there's an error causing the server to crash, this also happens upon reloading the server (multiple times)

Other fabric mods, Versions of those mods, JVM Flags, and other system info are available in the crashlog

**All other functions seem unaffected**

**Comment by MBatt1** [comment]
This is because the server is trying to call a class that only exists on the client side.

**Comment by MBatt1** [comment]
should be fixed in next version

**Comment by Simeonlps** [comment]
> This is because the server is trying to call a class that only exists on the client side. Oops

ah
well nowhere in hell would i have figured that one out myself xd

**Comment by MBatt1** [comment]
resolved in b1.0.3
