### ISSUE TITLE
Water improperly "paths" w.r.t. dense aercloud

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#188]
Water doesn't take dense aercloud fluid into account when "pathing" off a ledge. Likely won't be an easy fix.

![2021-04-15_18 59 03](https://user-images.githubusercontent.com/64770632/114961034-19dbaf80-9e1d-11eb-8633-6647f883311a.png)
![2021-04-15_18 59 11](https://user-images.githubusercontent.com/64770632/114961036-1a744600-9e1d-11eb-90b8-932e6dd07dd6.png)

Here you can see the path the water is trying to take:
![image](https://user-images.githubusercontent.com/64770632/114960907-d719d780-9e1c-11eb-99f5-c0d1539d8276.png)

**Comment by SollyW** [comment]
Why is dense aercloud a fluid anyway?

**Comment by Jack-Papel** [comment]
You'd have to ask Azzy for a more precise answer, but in short, there are plans for some sort of dense-aercloud ocean idea.
