### ISSUE TITLE
TechReborn Rubber trees spawn in the Aether

### ISSUE THREAD

**Issue by RedBumboo** [devs-immortal/The-Aether#194]
Don't know if this is an issue with Aether Reborn or TechReborn, but since Aether Reborn is a WIP I figured I'd put this here anyways.

**Comment by kalucky0** [comment]
I'm sure it's a problem with TechReborn. We could prevent it probably somehow, but they are the ones who should fix it.

**Comment by MBatt1** [comment]
Should determine if this is still a problem

**Comment by Azzyypaaras** [comment]
Was this really a problem to begin with? Rubber being available in the aether is not game breaking and arguably not immersion breaking, and it does contribute to the objective of allowing Aether-only runs.

**Comment by SollyW** [comment]
Can this be closed?

**Comment by Azzyypaaras** [comment]
In seven business days
