### ISSUE TITLE
Flying piglins in the Aether dimension

### ISSUE THREAD

**Issue by Degostor** [devs-immortal/The-Aether#198]
so I was playing around with quick soil and then my game crashed, reopened the game, joined my world and then piglin brutes started spawning all around the place, pillagers and ravagers spawned too, and there was a village too 
(srry for the terrible english)

![2021-04-22_15 22 21_2](https://user-images.githubusercontent.com/80651955/115792635-7be96700-a37f-11eb-860c-b07b83c06d82.png)
![2021-04-22_15 22 17_2](https://user-images.githubusercontent.com/80651955/115792646-7f7cee00-a37f-11eb-943e-20da8084dd4e.png)

![2021-04-22_15 22 15](https://user-images.githubusercontent.com/80651955/115792655-83a90b80-a37f-11eb-9834-a1d413afc1c6.png)
![2021-04-22_15 22 17](https://user-images.githubusercontent.com/80651955/115792661-860b6580-a37f-11eb-9af4-15f5e3c162d5.png)
![2021-04-22_15 23 23](https://user-images.githubusercontent.com/80651955/115792665-86a3fc00-a37f-11eb-8ac7-c9f04b1744c6.png)
![2021-04-22_15 22 26](https://user-images.githubusercontent.com/80651955/115792675-8b68b000-a37f-11eb-9562-42b690239a7f.png)
![2021-04-22_15 22 49](https://user-images.githubusercontent.com/80651955/115792702-99b6cc00-a37f-11eb-91ef-c59e2ffbf0e5.png)

**Comment by kalucky0** [comment]
Are you using any other mods?

**Comment by Degostor** [comment]
Yes, backslot, staff of building, emerald tools, sodium, phosphor and lithium

**Comment by MBatt1** [comment]
Looks like repurposed structures is installed, some other people have brought up this bug, it seems to be a problem with their mod, not the aether,

**Comment by Degostor** [comment]
okay, Im gonnna disable it, tysm
