### ISSUE TITLE
Every fluid collected by skyroot bucket becomes water

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#200]
Related to #187.
Code snippet containing the error:

In aether/items/tools/SkyrootBucket.java
`
if (fluid != Fluids.EMPTY) {
    playerIn.incrementStat(Stats.USED.getOrCreateStat(this)); 
    playerIn.playSound(SoundEvents.ITEM_BUCKET_FILL, 1.0F, 1.0F); 
    ItemStack fillStack = this.fillBucket(currentStack, playerIn, AetherItems.SKYROOT_WATER_BUCKET); 
`

**Comment by Jack-Papel** [comment]
On my end, Github didn't format the code correctly. Basically, this code treats every fluid as if it's water.

**Comment by Jack-Papel** [comment]
I would fix it myself, but I'm not sure what the proper interaction is with lava, dense_aercloud, etc.

**Comment by MBatt1** [comment]
It should only be able to pick up water. There is no skyroot lava bucket (because wood), and the dense aercloud is supposed to be picked up by whatever vial thing azzy made, but don't worry about that for now

**Comment by Jack-Papel** [comment]
Thanks. I'll write up a fix then

**Comment by kalucky0** [comment]
Fixed in #201
