### ISSUE TITLE
Game crashes when return from Aether

### ISSUE THREAD

**Issue by xireza** [devs-immortal/The-Aether#207]
I don't know exactly what triggered the crash: if it was the return with aether items in my invt or the merely returning.
Also, when reoppening my world, I spawned in another random chunk, not even close to the portal.
I'm leaving the crashlog here.
PD: Loved your work!

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 03/05/21 12:48 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.class_2189 cannot be cast to net.kyrptonaught.customportalapi.CustomPortalBlock
	at net.kyrptonaught.customportalapi.CustomPortalsMod.getPortalBase(CustomPortalsMod.java:74)
	at net.minecraft.class_746.handler$zcg000$injectCustomNausea(class_746.java:1283)
	at net.minecraft.class_746.method_18654(class_746.java)
	at net.minecraft.class_746.method_6007(class_746.java:665)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:205)
	at net.minecraft.class_638.method_18646(class_638.java:193)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_638.method_18116(class_638.java:164)
	at net.minecraft.class_310.method_1574(class_310.java:1556)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.kyrptonaught.customportalapi.CustomPortalsMod.getPortalBase(CustomPortalsMod.java:74)
	at net.minecraft.class_746.handler$zcg000$injectCustomNausea(class_746.java:1283)
	at net.minecraft.class_746.method_18654(class_746.java)
	at net.minecraft.class_746.method_6007(class_746.java:665)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:205)
	at net.minecraft.class_638.method_18646(class_638.java:193)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 11
	Entity Name: ireza
	Entity's Exact location: -57.58, 72.00, 54.57
	Entity's Block location: World: (-58,72,54), Chunk: (at 6,4,6 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_638.method_18116(class_638.java:164)

-- Affected level --
Details:
	All players: 1 total; [class_746['ireza'/11, l='ClientLevel', x=-57.58, y=72.00, z=54.57]]
	Chunk stats: Client Chunk Cache: 361, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,69,-192), Chunk: (at 0,4,0 in -5,-12; contains blocks -80,0,-192 to -65,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 283849 game time, 396698 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2662218712 bytes (2538 MB) / 3825205248 bytes (3648 MB) up to 3959422976 bytes (3776 MB)
	CPUs: 8
	JVM Flags: 10 total; -Xmn128M -Xmx3763M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.1
		artifacts: Artifacts 3.2.0+fabric
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cardinal-components: Cardinal Components API 2.8.1
		cardinal-components-base: Cardinal Components API (base) 2.8.1
		cardinal-components-block: Cardinal Components API (blocks) 2.8.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.1
		cardinal-components-item: Cardinal Components API (items) 2.8.1
		cardinal-components-level: Cardinal Components API (world saves) 2.8.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.1
		cardinal-components-util: Cardinal Components API (utilities) 2.8.1
		cardinal-components-world: Cardinal Components API (worlds) 2.8.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.19
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		crowdin-translate: CrowdinTranslate 1.2
		customportalapi: Custom Portals 0.0.1-beta29-1.16
		dynamicfps: Dynamic FPS 2.0.1
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.34.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		ferritecore: FerriteCore 2.0.4
		geckolib3: Geckolib 3.0.33
		go-fish: Go Fish 1.2.1-beta-1.16.4
		inmis: Inmis 2.2.1-1.16.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		magna: Magna 1.5.3-1.16.5
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.16.9
		omega-config: OmegaConfig 1.0.4
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		seedy-behavior: Seedy Behavior 1.0.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		the_aether: The Aether 1.16.5-1.0.3
		trinkets: Trinkets 2.6.7
		vanilla-hammers: Vanilla Hammers 3.0.3-1.16.5
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
	Launched Version: fabric-loader-0.11.3-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6444, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: Español (España)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by Jack-Papel** [comment]
@kyrptonaught Seems like an error with customportalapi

**Comment by kyrptonaught** [comment]
Trying to cast an block of air to the portal block, when attempting to apply the custom colored portal swirl nausea effect. Thought I had checks for this. Regardless though this shouldn't happen. You mentioned spawning someone completely different then where the portals was, after relog. Meaning you were at the portal before the crash?

**Comment by kyrptonaught** [comment]
Ah yep I missed a hard cast here: https://github.com/kyrptonaught/customportalapi/blob/main/src/main/java/net/kyrptonaught/customportalapi/CustomPortalsMod.java line 74

**Comment by xireza** [comment]
@kyrptonaught yep. It crashed exactly after reappearing in the overlord

**Comment by kyrptonaught** [comment]
Perhaps the reappearing random could be bc your new pos wasn't saved yet before the crash. I'll get this crash fixed though, and see if the other issue persists

**Comment by MBatt1** [comment]
Was this resolved with the new changes?

**Comment by kyrptonaught** [comment]
I'm working on the maven repo, should have it completed by tonight. Then I'll get this fixed and uploaded to the new repo.

**Comment by kyrptonaught** [comment]
I swear I did already have this fixed, turns out I committed the changes to the 1.17 branch 15 days ago. Beta32 has been released fixing this. Still working on the maven
