### ISSUE TITLE
Not generating a world

### ISSUE THREAD

**Issue by aleabla0** [devs-immortal/The-Aether#211]
I don’t know if this is the Aether reborn mod GitHub, but if it is, I keep having problems because whenever I decide to open or create a world, it starts generating it fine, arrives to 5-6%, and then it hardlocks. What can I do to resolve this problem?

**Comment by kalucky0** [comment]
Can you provide us the logs?

**Comment by aleabla0** [comment]
I’m not that smart and don’t know what logs are. I could provide you video
evidence.

Il giorno mar 11 mag 2021 alle 07:33 kalucky0 ***@***.***> ha
scritto:

**Comment by aleabla0** [comment]
Ok Then I will send you the logs as soon as I manage to get them

Il giorno mar 11 mag 2021 alle 14:37 kalucky0 ***@***.***> ha
scritto:

**Comment by SpGilbert** [comment]
having the same issue Only have 5 mods REI, aether, cloth config, fabric, and trinkets all the latest version I think.

**Comment by kalucky0** [comment]
Check #217
