### ISSUE TITLE
Aether Farmland Issue

### ISSUE THREAD

**Issue by SpinnyBoiii** [devs-immortal/The-Aether#213]
Was comparing farmland speeds of different mods compared to vanilla using small size auto-villager farms of 9x9 blocks and noticed that villagers wont plant on modded farmland like the aether farmland unless there's regular farmland in range

**Comment by CDAGaming** [comment]
Requires a mixin/accessor to Rabbit#isValidTarget and VillagerProfession to fix this from looking into it
