### ISSUE TITLE
texturepackbugs

### ISSUE THREAD

**Issue by sunny-gg95** [devs-immortal/The-Aether#227]
![texturepack1](https://user-images.githubusercontent.com/61912148/119260015-1812c200-bbfb-11eb-9a28-46b6f32cd23a.png)
![texturepack2](https://user-images.githubusercontent.com/61912148/119260017-1b0db280-bbfb-11eb-9f7a-c5726f690919.png)

**Comment by kalucky0** [comment]
Duplicate of #75
