### ISSUE TITLE
I try aether on server(Aternos) and I got this

### ISSUE THREAD

**Issue by sunny-gg95** [devs-immortal/The-Aether#228]
https://drive.google.com/file/d/1FZBex2rctF2mn3SWu5nPkV9JgsUSlDx9/view?usp=sharing
I don't know what to do.

**Comment by Jack-Papel** [comment]
This issue has occured in the past when the server didn't have the aether installed, or the client had differing mods to the server. 
From your video, it appears that you have a third page in your creative menu, indicating that you have more mods than the server. (The Aether only adds one page to the creative menu, and the server only has the aether, so another menu indicates another mod that the server doesn't have.)
This an issue with fabric itself, and unfortunately not something we can fix.
Thanks for the report! Have fun.
