### ISSUE TITLE
portal bug

### ISSUE THREAD

**Issue by sunny-gg95** [devs-immortal/The-Aether#229]
After https://github.com/devs-immortal/The-Aether/issues/228 I installed all the mods and got new bugs.

https://drive.google.com/file/d/1QZvGOmvh5rdd_f3jWYgItGUEk8fbpYSd/view?usp=sharing

**Comment by Jack-Papel** [comment]
At the moment, you have to travel through the portal a few times before it becomes an immersive portal. Try to be more descriptive with your issue titles/descriptions.
Thanks for letting us know! Have fun.
