### ISSUE TITLE
A little bunny doesn't compatible with orderly mod

### ISSUE THREAD

**Issue by sunny-gg95** [devs-immortal/The-Aether#237]
Aerbunny is not finished yet.
![2564-05-27_20 46 08](https://user-images.githubusercontent.com/61912148/119837748-10ba2400-bf2d-11eb-9fc6-7e1b5cdafe81.png)

**Comment by MBatt1** [comment]
We need to make lang files for mobs

**Comment by kalucky0** [comment]
I'll add new strings to Crowdin today

**Comment by sunny-gg95** [comment]
![image](https://user-images.githubusercontent.com/61912148/120134667-d71d3d80-c1f8-11eb-9a81-5a62a61d6682.png)

**Comment by CDAGaming** [comment]
Resolved in 1.17 port.
