### ISSUE TITLE
Aether Structures spawn in "End"

### ISSUE THREAD

**Issue by DaisukeVN** [devs-immortal/The-Aether#239]
Is it possible to disable structure generation in dimensions or can you disable it for "End" Dimension?

![2021-05-27_22 31 11](https://user-images.githubusercontent.com/4640928/119900318-a9a86980-bf44-11eb-8948-41462bac5a13.png)

**Comment by MBatt1** [comment]
This is fixed in the new release from today, just update the mod to [beta 1.0.4](https://github.com/devs-immortal/The-Aether/releases/tag/b1.0.4)
