### ISSUE TITLE
Custom Portal API

### ISSUE THREAD

**Issue by bobdoby** [devs-immortal/The-Aether#242]
Hey guys, i know this is not your issue but i thought you guys would be kind enouph to give me some advice ?

i was wondering how you guys managed to get your custom portals api to work iwth your mod, i just kept getting issues when i tried to add the repository
this is what i did

repositories {
maven { url "http://maven.kyrptonaught.dev" }

	mavenCentral()
}
dependencies {
modImplementation "net.kyrptonaught:customportalapi:${project.customportalapi_version}"
include "net.kyrptonaught:customportalapi:${project.customportalapi_version}"

	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	
}

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'customportalapi_version' for root project 'fabric-example-mod-master' of type org.gradle.api.Project.

**Comment by kalucky0** [comment]
@kyrptonaught will help you on his [Github page](https://github.com/kyrptonaught/customportalapi/issues/24) or on Discord.
