### ISSUE TITLE
Aerwhales spawning in overworld

### ISSUE THREAD

**Issue by cavy8** [devs-immortal/The-Aether#244]
I'm having aerwhales spawning in the overworld with 1.4.1

**Comment by MBatt1** [comment]
I think this is probably aewhales falling from the aether, sometimes they will spawn and fall

**Comment by CDAGaming** [comment]
Resolved in 1.17 branch

**Comment by ketufaispikinut** [comment]
https://github.com/devs-immortal/The-Aether/pull/306
Attempt to fix the whales going down y20, so they wont reach overworld.
