### ISSUE TITLE
Aerclouds produce shadows

### ISSUE THREAD

**Issue by Crackers0106** [devs-immortal/The-Aether#245]
In both the official versions of the Aether by Gilded Games, aerclouds are transparent blocks like glass and do not produce shadows. However in Aether Reborn they do produce block shadows causing lots of ugly dark spots in the Aether.
Resolving this might also cause a slight performance increase due to there not being as many shadows that need to be calculated on the lighting engine

The file BaseAercloudBlock.java also has a tag saying it should be non-opaque, however other references to aerclouds I could find don't, so I'm inclined to say this is a bug

This bug is most visible on Moody brightness

![2021-06-13_00 24 02](https://user-images.githubusercontent.com/32655060/121795361-f1362300-cbdd-11eb-92cf-13b5bc692f2b.png)

**Comment by CDAGaming** [comment]
Please attach a screenshot for a clear reference, as from my end this does not seem to be occuring.

**Comment by CDAGaming** [comment]
For the most part, after extensive testing, I believe this is resolved within the 1.17 branches, so I'll mark this as resolved. I'll leave the issue open in case this gets backported (Or someone else wants to close this)
