### ISSUE TITLE
Make certain aether blocks have a chance to drop ambrosium shards

### ISSUE THREAD

**Issue by Crackers0106** [devs-immortal/The-Aether#247]
In the original Aether, when mining certain natural blocks, there's a rare chance they will also drop an ambrosium shard along with their usual drop. As far as I know this happens on: Holystone, Aether Grass, and Aether Dirt

**Comment by MBatt1** [comment]
This doesn't have much vanilla parity, but we do have ambrosium ore spawning more frequently than the original, which kinda makes up for it.
