### ISSUE TITLE
can you please make a forge port?

### ISSUE THREAD

**Issue by NZgamer2008** [devs-immortal/The-Aether#249]
i would really like to use this with my other forge mods, if you cant make a port i understand, just asking

**Comment by Jack-Papel** [comment]
Gilded Games is working on The Aether for forge 1.16+: https://github.com/Gilded-Games/The-Aether

**Comment by MBatt1** [comment]
Read the faq in our discord for some more information if you'd like

**Comment by NZgamer2008** [comment]
thanks! i tested it out with immersive portals and it mostly works!
