### ISSUE TITLE
[Bug] Crashes for no reason

### ISSUE THREAD

**Issue by MenacingPerson** [devs-immortal/The-Aether#261]
When trying to load a world, it crashes. The little square animation that plays when you load a world has holes in it and the percentage is stuck. After that it freezes and i have to use task manager to kill it.

Fabric 0.11.3
Fabric api 0.35.0
Trinkets 2.6.7
Minecraft 1.16.5
Both aether 1.0.4 and 1.4.1 have this issue.

![image](https://user-images.githubusercontent.com/59611020/121815243-0620be00-cc93-11eb-982e-4e8cf06b90b5.png)

**Comment by MenacingPerson** [comment]
These are the only mods i have other than fabric language kotlin

**Comment by Jack-Papel** [comment]
You need to use fabric API 0.33.x or lower

**Comment by MenacingPerson** [comment]
oh ok

**Comment by MenacingPerson** [comment]
it works!
