### ISSUE TITLE
Concurrent Modification for White Swet

### ISSUE THREAD

**Issue by DabbingEevee** [devs-immortal/The-Aether#262]
The white swet causes a forloop to happen, and you are removing effects while it is parsing through the different effect.

to fix:

Create an empty ArrayList<StatusEffectInstance> and add all of the player’s status effects. then parse through this new arraylist and remove player effects accordingly. Hopes this helps.

**Comment by Jack-Papel** [comment]
I took a peek at the code, and I don't believe this is the case. I'll look into it later when I'm at my computer though

**Comment by CDAGaming** [comment]
Looking at it as well, I agree with @Jack-Papel and I havent seen any such issue.

Furthermore, this was the result, when I formatted PR #267 
![image](https://user-images.githubusercontent.com/16328918/121973795-a7ffe380-cd43-11eb-96cb-da5a9c583c7c.png)

The result is identical, but with a bit more overhead shoving everything into a new list...

**Comment by Jack-Papel** [comment]
After some review and testing, it seems that this is indeed an issue in some circumstances.
