### ISSUE TITLE
Using Aether Reborn with Space Dimensions overrides default skybox

### ISSUE THREAD

**Issue by filipesn** [devs-immortal/The-Aether#269]
Using the latest version with https://www.curseforge.com/minecraft/mc-mods/moon-and-space-dimensions-fabric (also latest version) makes the Aether use the wrong skybox
This might be a problem on their side, but i don't know

**Comment by filipesn** [comment]
![dad](https://user-images.githubusercontent.com/40408605/122142288-89721900-ce25-11eb-933d-bfc7e42e8b4f.png)

**Comment by CDAGaming** [comment]
This likely is an issue on their end, especially if its a case of THEIR skybox overriding ours and not vice versa.

**Comment by filipesn** [comment]
I will post the issue on their mod as well

**Comment by filipesn** [comment]
He said he is going to fix it soon, and provided a temporary fix, so im closing the issue

**Comment by MindForged** [comment]
Can confirm this issue still exists in the most recent version of Space Dimensions. I experienced The End overwriting the skybox and mob spawns in the Aether, and space dimensions slightly filtering into the the overworld. The dev mentioned the dimensions "being defined using datapack method", which I assume is the cause. The dev said they're likely going to mark these 2 mods as incompatible.

![image](https://user-images.githubusercontent.com/33333985/129844736-5881c58e-b698-463a-867f-93be794a1ea8.png)
