### ISSUE TITLE
Using Skyroot Milk Bucket crashes game

### ISSUE THREAD

**Issue by IMS212** [devs-immortal/The-Aether#27]
https://pastebin.com/NEN1CmbW crash report

**Comment by CDAGaming** [comment]
java.lang.ClassCastException: class net.minecraft.server.network.ServerPlayerEntity cannot be cast to class com.aether.api.player.IEntityPlayerAether (net.minecraft.server.network.ServerPlayerEntity and com.aether.api.player.IEntityPlayerAether are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @7c137fd5)

This likely will end up fixing itself once more of the api gets actually impl back into this, though it could be band-aid fixed if needed

**Comment by Dragonoidzero** [comment]
Fixed. Also went ahead and knocked out butchering the deprecated parts of the API, those being all of it.
