### ISSUE TITLE
Cobbled Holystone can't be obtained

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#275]
Mining cobbled holystone with a pickaxe does not drop the block. Cobbled holystone also cannot be levitated by gravitite tools.

**Comment by Jack-Papel** [comment]
Should be resolved by https://github.com/devs-immortal/The-Aether/commit/d4df2107824861b99df51a23998ff3b3aff36364

**Comment by CDAGaming** [comment]
Confirmed resolved in server scope.
