### ISSUE TITLE
FloatingBlockEntities don't always land in the right spot

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#280]
Very rare issue. To replicate:
Create a superflat world
Place down a block of your choice
Place a ceiling 5 blocks above it as shown in the video:

https://user-images.githubusercontent.com/64770632/122853270-ce36fd80-d2c6-11eb-977a-cdcfc8b2fe81.mp4

**Comment by Jack-Papel** [comment]
Also happens at these heights:

![image](https://user-images.githubusercontent.com/64770632/131289394-e4054157-0111-4142-86e0-a00c3efbc0ca.png)

Probably some rounding or precision issue

**Comment by CDAGaming** [comment]
Doesn't seem to occur anymore in latest dev release, assumed fixed for 1.6

**Comment by Jack-Papel** [comment]
A similar issue seen on latest commit - likely with the same cause. Reopening

**Comment by gudenau** [comment]
![image](https://user-images.githubusercontent.com/5642329/154408051-894692a9-e797-4030-bfe5-c9d5ad21f304.png)
Can not reproduce.

**Comment by Jack-Papel** [comment]
CDA's friend reproduced it in one of the dev builds. Go to around y=64 (I forget the exact value) and make it float up one block.

**Comment by gudenau** [comment]
![image](https://user-images.githubusercontent.com/5642329/154419129-3f36050d-9d0b-40ee-95d6-506ce0c89650.png)

**Comment by Jack-Papel** [comment]
Huh. Maybe it's fixed itself. What version of the mod are you running in these screenshots?

**Comment by CDAGaming** [comment]
Wha....How in the f--, Ok, I won't question this xD

**Comment by gudenau** [comment]
> Huh. Maybe it's fixed itself. What version of the mod are you running in these screenshots?

367d7b7ee008d74c697f27a61e61039b22b7d052
