### ISSUE TITLE
FloatingBlockEntities inconsistently breaking on slabs

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#282]
In my testing, I have found that FloatingBlockEntities never break on slabs when ascending, but always break on slabs when descending.

**Comment by CDAGaming** [comment]
Still present in current build, bumped.

**Comment by MBatt1** [comment]
frankly 
![current mood](https://github.com/devs-immortal/Paradise-Lost/assets/53229958/d9811dfa-4209-4cd9-b24f-8a6ea2c2cfcd)
