### ISSUE TITLE
FloatingBlockEntities' landings are jerky

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#285]
See videos.
FloatingBlockEntities land very discontinuously

https://user-images.githubusercontent.com/64770632/122858059-7ac8ad80-d2ce-11eb-87ed-a7d35660c1d8.mp4

https://user-images.githubusercontent.com/64770632/122858119-98961280-d2ce-11eb-8ef4-0aff436614d9.mp4

**Comment by Jack-Papel** [comment]
Reviewing the footage, it seems the half-a-block-early figure wasn't exactly accurate. The entity seems very disconnected from the landing though, likely due to its disappearance right before landing.

**Comment by CDAGaming** [comment]
Marked as excess since tbf FallingBlocks also have this same issue.
