### ISSUE TITLE
Door <-> FloatingBlockEntity Issues

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#287]
When the top half of a door is turned into a floating block, it will drop an item (Since the bottom half gets destroyed). When the top half of the door lands, it will drop another door item, which duplicates one door into two.

**Comment by MBatt1** [comment]
We should probably have a blacklist on all multi-block things like beds and doors

**Comment by Jack-Papel** [comment]
We're discussing how to handle tall blocks in #developers

**Comment by CDAGaming** [comment]
Marked as resolved via workaround.
