### ISSUE TITLE
Lag near rainbow wisterias

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#326]
As reported by SlimeFarmDuDe on the discord.

**Comment by Azzyypaaras** [comment]
...is there a log, further info, anything?
He is so far the only person reporting this.

**Comment by Jack-Papel** [comment]
I'll ask for more info.
I do believe he is telling the truth though, thinking back to how I wrote the code.

**Comment by Azzyypaaras** [comment]
:concern:
