### ISSUE TITLE
Skyroot towers generate in the air

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#328]
Seed `2263071025290849782` at `-2128, 3568`, 1.17 branch
![The tower](https://user-images.githubusercontent.com/37163416/124890927-de1b4500-e01b-11eb-81e0-69885e646cb2.png)
`384, 432`
![Another tower](https://user-images.githubusercontent.com/37163416/124892057-de681000-e01c-11eb-98f2-8338b5c06232.png)

**Comment by MBatt1** [comment]
This can happen but it is uncommon, however there isn't much we can do about it, there will always be a chance of overhanging if it generates in certain circumstances

**Comment by CDAGaming** [comment]
Please re-confirm in 1.6.0
