### ISSUE TITLE
Quicksoil generation cuts off on chunk borders

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#329]
![screenshot_2021-07-08T18:48:10](https://user-images.githubusercontent.com/37163416/124892709-7108af00-e01d-11eb-8aee-f93991a71a63.png)
![screenshot_2021-07-08T18:48:36](https://user-images.githubusercontent.com/37163416/124892723-7534cc80-e01d-11eb-8ad0-d98afd13f932.png)
![screenshot_2021-07-08T18:49:28](https://user-images.githubusercontent.com/37163416/124892740-78c85380-e01d-11eb-80d4-74c40ea78928.png)
![screenshot_2021-07-08T18:50:06](https://user-images.githubusercontent.com/37163416/124892809-8b428d00-e01d-11eb-8e4f-1b3693de9c70.png)

**Comment by MBatt1** [comment]
This is because of how it expands outwards, it should probably be limited

**Comment by MBatt1** [comment]
This feature seems to be incredibly inefficient when finding blocks to place, but more work needs to be done to prevent cut off chunk border edges, reducing the maximum distance from 24 to 16 has helped.
