### ISSUE TITLE
Aerbunnies block the player's view when picked up

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#338]
This doesn't seem intentional, as the interior of the bunny can be seen

**Comment by reoseah** [comment]
They should override `getHeightOffset` to add to their height when mounted. Instead, they override `getMountedHeightOffset` which adds to offset of an entity which `rides` the bunny... So, that's an easy fix

These two methods are confusing, I think Yarn should rename them or add javadoc to both of them telling what they do...

**Comment by reoseah** [comment]
Fixed in https://github.com/devs-immortal/The-Aether/commit/9be012d086b0ae862d444ab3792def9dc765d699
