### ISSUE TITLE
Aerbunnies shouldn't walk

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#340]
The walk animation on aerbunnies looks awakward - as if they're sliding along and wriggling their legs. They should hop around like vanilla rabbits.

**Comment by reoseah** [comment]
Wait, wrong issue, I meant to close https://github.com/devs-immortal/The-Aether/issues/338

**Comment by MBatt1** [comment]
Aerbunnies are soon to be removed. Closing
