### ISSUE TITLE
Missing wooden blocks

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#342]
Orange, skyroot, golden oak, crystal, and wisteria lack:

- [x] Wood and Stripped Wood (bark texture all sides)
- [x] Signs
- [x] Boats
- [x] Pressure Plates
- [x] Buttons
- [x] Skyroot chest
- [ ] Orange chest
- [ ] Golden Oak chest
- [ ] Wisteria chest
- [ ] Crystal chest

**Comment by Jack-Papel** [comment]
First bullet point taken care of by this commit: https://github.com/devs-immortal/The-Aether/commit/dab834bf1aca98a2b9f7336bc596cec47efabd64

**Comment by Jack-Papel** [comment]
[moved this check box to the original message so GitHub can do the task list properly]

**Comment by Azzyypaaras** [comment]
Not just skyroot, do not allow 24 to gaslight you :tater:

**Comment by MBatt1** [comment]
only skyroot? okay sounds good to me
