### ISSUE TITLE
Perpetual speed buildup on quicksoil panes

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#344]
When shifting on quicksoil glass panes, you can perpetually build up speed on the edge of a pane. This is because when on the edge of a pane, you are still over the same blockpos. This doesn't happen on quicksoil blocks because you change blockpos

**Comment by Jack-Papel** [comment]
(Or at least, I imagine that's what's causing it)

**Comment by Jack-Papel** [comment]
Oh, by edge of a pane I mean like an end. You'll be stationary, see the screen do the fast speed fov effect, and when you unshift you'll go flying off.

**Comment by Azzyypaaras** [comment]
Is fixing this going to require talking about parallel universes?

**Comment by Jack-Papel** [comment]
Ah, it's not a bug - it's just a sequence break for speedrunners

**Comment by Jack-Papel-RIT** [comment]
Needs confirmation in 0.2.0
