### ISSUE TITLE
Aether mobs not loading

### ISSUE THREAD

**Issue by SirElCid** [devs-immortal/The-Aether#345]
Hello,

I've recently installed the aether reborn mod on the server, however every time it loads, it says it's missing several entities.

[main/ERROR]: No data fixer registered for aechor_plant
[main/ERROR]: No data fixer registered for flying_cow
[main/ERROR]: No data fixer registered for aerbunny
[main/ERROR]: No data fixer registered for moa
[main/ERROR]: No data fixer registered for phyg
[main/ERROR]: No data fixer registered for sheepuff
[main/ERROR]: No data fixer registered for cockatrice
[main/ERROR]: No data fixer registered for chest_mimic
[main/ERROR]: No data fixer registered for golden_dart
[main/ERROR]: No data fixer registered for enchanted_dart
[main/ERROR]: No data fixer registered for poison_dart
[main/ERROR]: No data fixer registered for poison_needle
[main/ERROR]: No data fixer registered for aerwhale
[main/ERROR]: No data fixer registered for blue_swet
[main/ERROR]: No data fixer registered for purple_swet
[main/ERROR]: No data fixer registered for white_swet
[main/ERROR]: No data fixer registered for golden_swet

Is this normal? Are they going to be added on a future update?

**Comment by BLovegrove** [comment]
Would like to add to this and say that whenever I try to use a moa egg to force a spawn my game crashes. Aerbunny works, cockatrice has a missing textures and aechor plants are invisible. Aerwhale and most other mobs can be summoned with the /summon command as normal (including moas, strangely enough). Log attached.
[log.txt](https://github.com/devs-immortal/The-Aether/files/6795144/log.txt)

**Comment by Jack-Papel** [comment]
We still have to fix the missing data fixer log issue, but for the most part, if you try to spawn something, it should work. See #232 for progress on mobs, or check out the Mob Development project in the Projects tab. Thanks for bringing this to our attention.
Pertaining to BLovegrove's issue, Cockatrice and Aechor plants aren't fully implemented yet. We've also heard several reports of moa eggs not working, and are looking for ways to replicate and squash the bug. Did you use a moa egg from the creative menu or was it naturally dropped from a moa?

**Comment by Azzyypaaras** [comment]
@BLovegrove Your issues are unrelated to the data fixer issues. Aechor plants and cockatrices are incomplete, moa eggs are known to crash because a certain someone partially implemented them without consulting the rest of the team.

**Comment by SirElCid** [comment]
I see. Thanks for the quick response. I'll wait for a future update.

**Comment by BLovegrove** [comment]
Ditto on the thanks for such a quick response! @Jack-Papel the egg was from the creative menu

**Comment by Jack-Papel** [comment]
Thanks for the info

**Comment by Jack-Papel** [comment]
After some further research online, and some guidance from CDA, this data fixer issue doesn't seem worth fixing. It's not really an issue, and there's not really a neat way to fix it. Almost every mod that adds entities has this bug too, according to my sources.
The moa egg issue is being worked on, as moas are being overhauled in the next update. 
Thanks for reporting these issues! Have fun in The Aether.
