### ISSUE TITLE
Aether Water transparency messes up on loading chunks

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#348]
![image](https://user-images.githubusercontent.com/53229958/125176771-e7332000-e19b-11eb-935d-5a8dd6f9d95b.png)

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/143076726-1c6c13f6-dafc-4423-b15f-ac5087902881.png)
Bumped, still present in 1.6.0

**Comment by MBatt1** [comment]
Technically this is no longer an issue, because water springs do not generate any more
