### ISSUE TITLE
Falling out of the Aether spawns you at world height

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#351]
It should probably be higher, such that if there's a platform built at world height you can't just land and be fine

**Comment by Azzyypaaras** [comment]
Change it to twice the world height.
If the world is 4k blocks tall then be prepared to fall for a hot moment :yeef:

**Comment by Jack-Papel** [comment]
Made it 320 blocks above world height. Lmk if it's too long or too short a fall.
