### ISSUE TITLE
Enchanting table shows particles from skyroot bookshelves, but does not grant higher enchantment level

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#355]
Good luck with this one, bookshelves are hardcoded bad

**Comment by SollyW** [comment]
Challenge accepted :)

**Comment by Azzyypaaras** [comment]
![hmmmm](https://user-images.githubusercontent.com/20349662/126592887-7f5aef0e-1d03-48c6-99f0-6e13fa37fe25.jpg)

**Comment by SollyW** [comment]
It seems this was already fixed in the past, but was disabled in a [seemingly unrelated commit](https://github.com/devs-immortal/The-Aether/commit/9ac98ccc221c368766555450d3b2e690a4b94182#diff-e7f01356f6e54fbebe0b157c0f36f43360b624768be235607b42d046509a2f7e). Does anyone know why?

**Comment by Azzyypaaras** [comment]
Perhaps CDA knows?

**Comment by SollyW** [comment]
I uncommented the mixin, and it works fine ¯\\\_(ツ)\_/¯

**Comment by SollyW** [comment]
Resolved
