### ISSUE TITLE
Icestone doesn't do anything

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#357]
According to the aether wiki, it originally froze water into ice that touches it (?)

**Comment by MBatt1** [comment]
There was a suggestion by @Dragonoidzero to have it apply freezing to adjacent enemies

**Comment by CDAGaming** [comment]
With the new conditional system, this should be plausible as a 1.7 or 1.8 feature

**Comment by MBatt1** [comment]
Icestone has been removed entirely, closing
