### ISSUE TITLE
Can't download newest version from modrinth.

### ISSUE THREAD

**Issue by RDKRACZ** [devs-immortal/The-Aether#36]
"Request failed with status code 403
An error occurred! Click this text to go back home, and find your way back!"

I was trying for a few days and still the link doesn't work.
Why there isn't a curseforge page?

**Comment by diabolical17** [comment]
There is a curseforge see the readme.

**Comment by diabolical17** [comment]
Thats also a modrinth problem.

**Comment by diabolical17** [comment]
https://www.curseforge.com/minecraft/mc-mods/aether

**Comment by diabolical17** [comment]
Our curseforge is on read only mode, see latest release on github release tabs.

Forgot to say 👌
