### ISSUE TITLE
Gravitite tools can be used to obtain unobtainable item forms of blocks

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#362]
Levitating a budding amethyst block, farmland block, path block, chorus plant, or infested block into an invalid landing space causes it to drop as an item

**Comment by SollyW** [comment]
A way of getting around this, as well as fixing universal silk touch, candles and pickles only dropping one item, flower pots not dropping, etc. is to simulate the block being broken by the gravitite tool that levitated it instead of using falling sand behaviour

**Comment by Jack-Papel** [comment]
This is the solution we were thinking of too. If you'd like to code it up, it'd be much appreciated.

**Comment by SollyW** [comment]
I'll have a look at it. No promises though
