### ISSUE TITLE
Let swets be leadable

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#374]
It would be very fun. Probably only do this one if there's some sort of leadable entity interface

**Comment by SollyW** [comment]
Leashing can be controlled by overriding methods in MobEntity, which swets do extend from (SwetEntity -> SlimeEntity -> MobEntity); however, the actual logic to control the leash moving the entity, breaking, etc. is implemented in PathAwareEntity, a subclass of MobEntity, which slimes and swets do not inherit from. To allow leading swets, the logic would have to be reimplemented.

**Comment by CDAGaming** [comment]
Coming to a 1.6 release near you!!!
