### ISSUE TITLE
Redstone components remain powered/pushed upon landing

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#379]
Redstone components should possibly be exempted from being floating blocks, unless there's a nice way to solve this issue.

**Comment by gudenau** [comment]
They appear to update to me, is there a way to trigger this?

**Comment by gudenau** [comment]
Oh, repeaters do it.

**Comment by Jack-Papel** [comment]
The issue occurs for redstone dust as well

**Comment by gudenau** [comment]
When I tried it on dust it worked fine.

**Comment by Jack-Papel** [comment]
Break the redstone torch after you float it

**Comment by gudenau** [comment]
I placed the dust on a block, floated it, broke the block, and it updated just fine on landing.

**Comment by Jack-Papel** [comment]
I mean powered-wise. Maybe the bug has been resolved though. Let's speak in dev chat
