### ISSUE TITLE
Spawning an Aerbunny makes block/item in hand, particles (like falling leaves) and nearby mobs jump

### ISSUE THREAD

**Issue by Sajuczen** [devs-immortal/The-Aether#38]
It also changes hitbox of blocks (shows a hitbox a little bit above block)

**Comment by CDAGaming** [comment]
This is due to it's model not being fixed just yet. It'll be replaced with a new model to fix this.

**Comment by CDAGaming** [comment]
Assigned, Fix is pending on @Dragonoidzero new model for the aerbunny

**Comment by Jack-Papel** [comment]
Spawning many aerbunnies causes them to jerk about quite a bit
https://user-images.githubusercontent.com/64770632/107870630-ebf2e280-6e4e-11eb-80c4-a3a05b1be964.mp4

**Comment by MBatt1** [comment]
Solved by new model
