### ISSUE TITLE
Game won't start / Crash with Trinkets

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#381]
## **If you're having this issue, here's what you should do:**

If you have Aether Reborn 1.5.0 and Trinkets 3.0.0 installed, you need to uninstall Trinkets. For technical reasons, trinkets is incompatible with our mod. We intend to fix this for the next update, but until then it cannot be used alongside our mod.

### **Still having issues?**

Does the game crash screen say something along the lines of: 
`Error: java.lang.NoSuchMethodError: 'blablabla.trinkets.blablabla...'`?

This means you have another mod installed that requires trinkets. Unfortunately, there is no way around this issue other than removing the other mod or removing this mod. (Hopefully you choose to keep this mod) :)

This is a temporary issue. We'd like to solve this as soon as possible, but we have to wait for Trinkets to update to 1.17.1.
Thanks for understanding. If you have any more questions, or these instructions didn't work for you, leave a comment.

**Comment by CDAGaming** [comment]
Trinket 3.0.1 should be used for 1.17.1, marked as resolved.

**Comment by Jack-Papel** [comment]
Trinkets 3.0.2 has also been released, and is preferable, as it fixes an important issue regarding experience.

**Comment by CDAGaming** [comment]
Closing as resolved, and doesnt necesarily need an aether update to be closed.
