### ISSUE TITLE
Aether portal can be created in the end

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#382]

**Comment by Jack-Papel** [comment]
I believe Kyrptonaught is already aware of this, and is working on it, so I won't move this issue over to his GitHub.

**Comment by kyrptonaught** [comment]
This has been implemented in beta-38. If you switch to using CustomPortalBuilder to create and register the portal, it has a call for only being ignitable in the overworld.
See [CustomPortalBuilder](https://github.com/kyrptonaught/customportalapi/blob/1.17/src/main/java/net/kyrptonaught/customportalapi/api/CustomPortalBuilder.java) Line-160
I'd recommend waiting for beta-39 tonight for the dispenser portal fixes as well.
