### ISSUE TITLE
Flying moas can get stuck on the side of blocks

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#385]
Flying a moa into the side of a block can sometimes cause it to get stuck, requiring the movement keys to be released in orded to move again. This issue appears to be more common with a faster moa.
![screenshot_2021-07-16T16:56:57](https://user-images.githubusercontent.com/37163416/125906410-d3fac5e4-2473-47dd-8ad3-90c7ed870961.png)

https://user-images.githubusercontent.com/37163416/125907087-1bee206f-9091-4243-9395-afc96c39f1de.mp4

**Comment by CDAGaming** [comment]
This is resolved within the https://github.com/devs-immortal/The-Aether/tree/feature/1.17%2Fexperiment-moa-revisions branch, due to the additions relating to stepHeight. CC @Jack-Papel to attempt merging this data into main branch.

**Comment by Jack-Papel** [comment]
Was this resolved?

**Comment by Jack-Papel** [comment]
Was this resolved?
