### ISSUE TITLE
Picking up aether logs does not grant recipe book recipes

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#389]
Vanilla logs unlock the wood and plank recipes when picked up. Aether logs do not. This issue applies to other items as well, such as planks

**Comment by gudenau** [comment]
Looks like this is just creating a boat load of JSON files.

**Comment by CDAGaming** [comment]
Oh, how this aged like milk 
![image](https://user-images.githubusercontent.com/16328918/152660280-860b79e3-3634-4b84-a360-2a58395823e9.png)

**Comment by CDAGaming** [comment]
This issue has been *partially* resolved for b1.6.5, and will be finalized in b1.7

b1.6.5 only will have recipe book support for the plank, bark, boat, and slab recipies for wood types (Enough for a started player). It is subject to team approval whether this should be extended to all blocks, or kept as is to retain some complexity.

**Comment by Jack-Papel** [comment]
This has been fixed in 1.6.5+. Thanks for reporting!
