### ISSUE TITLE
Larger swets should drop more swet balls

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#391]
big swet has more swet, so more swet is needed

**Comment by MBatt1** [comment]
also may want to look at the actual coloring of swet balls

**Comment by Azzyypaaras** [comment]
No

**Comment by Azzyypaaras** [comment]
The main problem I see here is that giving different swet balls different colors will prevent them from stacking together even if done via nbt and color providers, which is not exactly a great thing unless each color has its own properties.

**Comment by SollyW** [comment]
I created a system a while ago to allow different colours for items without preventing them from stacking, by simply allowing a stack to merge into a stack of a different colour - think terraria slime. I used it for parrot feathers and coloured shulker shells - but if I can find the source code again, it may be useful here

**Comment by Jack-Papel** [comment]
If you can find it, I think it'd be useful, and would make things look very nice.
