### ISSUE TITLE
Nether Generation is Majorly Affected

### ISSUE THREAD

**Issue by SalvieMundi** [devs-immortal/The-Aether#401]
When using this mod, Nether generation is affected. I have done a lot of testing and can confirm that the simple removal or addition of this mod majorly affects generation.

With this mod, most biomes aside from the nether wastes are rare to the point of being thousands of blocks out of range. In the case of the basalt deltas, they don't appear to even generate at all in any capacity. Generation of the overworld and end is arguably, though negligibly, also affected. Removing the mod results in normal generation.

**Comment by Azzyypaaras** [comment]
Right right.
This demands a new label

**Comment by kalucky0** [comment]
![obraz](https://user-images.githubusercontent.com/10831698/126381046-44d98383-f450-407b-9d36-0fbc7c40547a.png)

**Comment by SalvieMundi** [comment]
I'll get back to you with specifics, images or video of the issue, and a list of my mods later tonight. Busy atm.

**Comment by SalvieMundi** [comment]
LIST OF MODS
![image](https://user-images.githubusercontent.com/76707320/126396718-b3fc3426-58e3-4bb9-96fb-e16fe9d1e6b3.png)

This is my list of mods (other than the Aether Reborn mod):
Adorn
Appleskin
Architectury
Autosmelt Enchant
BCLib
Bee Buddy
Better Dropped Items
Better End
Better F3 
Better Strongholds
Better Third Person
Cave Biome API
Chat Heads
Cloth Config
Croptopia
Dark Paintings
Dawn API
Fabric API
Kotlin
Falling Leaves
FerriteCore
GeckoLib
Grizzly Bear Mob
Hydrogen
Immersive Portals
Lithium
Lovely Snails
ModMenu
More Villagers
Not Enough Animations
NPC Variety
Outvoted
Patchouli
Pig Steel
Promenade
Repurposed Structures
Roughly Enough Items
Starlight
Stoneholm
Terrarian Slimes
TransliterationLib
Trinkets
Untitled Duck Mod
Vanilla Degus
Vanilla+ Biomes
Wolves With Armor
Woods & Mires
WTHIT
Yet Another Tweak Mod
Yung's API

Unless the mod page specifically states client only with no additional features from server side installation, assume these are all on both the server and client.



ISSUE SPECIFICS / TESTING
The issue is that nether biomes other than the nether wastes become extremely rare and -- in the case of the warped forest and basalt deltas -- sometimes never generate at all. I actually didn't know this was happening at first, as I was just rapidly testing different features to make sure the server was stable. Once I noticed how bizarrely long the nether wastes were stretching on for, I actively looked for all nether biomes and couldn't find anything other than a soul sand valley in a 10000 block radius from my nether portal. I know that this weird generation is occurring due to something in the Aether mod because I tested as follows:

1. Remove a single mod from both server and client
2. Completely delete .fabric folders and world folder
3. Reboot server and client
4. Connect to the new world
5. Go straight to nether using a vanilla nether portal
6. Type /locatebiome minecraft:basalt_deltas or /locatebiome minecraft:warped_forest and see if either generated within ~5000 (iirc) blocks
7. If issue unresolved, put mod back and repeat process with another mod (testing only one mod at a time)

I ran this test for the following mods (I assumed other mods would be causing the issue first) and the issue didn't resolve or improve at all:
Promenade -- adds some nether biome variants, figured they might be over-riding the vanilla ones entirely
Pig Steel -- adds nether ores, thought generation might be affected
Repurposed Structures -- adds structures to the nether, thought it might affect generation

I then started looking at overworld and end generation mods:
BetterEnd -- removing this did not change the issue
Vanilla+ Biomes -- removing this did not change the issue
Cave Biome API -- removing this appears to have affected the issue, as biomes like soul sand valley and crimson forest became relatively common; but the nearest warped forest was over 5000 blocks from my nether portal and basalt deltas seemingly didn't generate

Finally got to the Aether Reborn mod. Removing this mod completely fixed the issue. All nether biomes started rendering in a seemingly vanilla fashion within roughly 500 blocks of the nether portal. After exploring the overworld, it seems like the generation there was a little less erratic as well -- I had been getting a relatively large amount of small, sky islands. More than I've been used to recently since 1.16.5. Removing the Aether mod seems to have stopped generating as many of those in the overworld.

Sorry this is pretty long winded and without a lot of screenshots, but I honestly don't want to go through the process of destroying the world, stopping the server, adding the mod, getting screens of the problem, doing it all again without the mod etc. etc.. Not saying that this couldn't be a weird mod interaction / incompatibility, but the root problem definitely seems to be coming from Aether Reborn.

**Comment by sunsetbear** [comment]
what

**Comment by ghost** [comment]
JESSE

**Comment by Jack-Papel** [comment]
Worldgen has majorly changed. Please reopen or update if the issue still occurs
