### ISSUE TITLE
Add Slider Dungeon

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#402]
- [ ] Structure
- [ ] Sliders
- [ ] Slider Boss
- [ ] Loot tables for chests

**Comment by youmukonpaku1337** [comment]
can't wait

**Comment by MBatt1** [comment]
No longer a dungeon we are allowed to make

**Comment by youmukonpaku1337** [comment]
> No longer a dungeon we are allowed to make
what???

**Comment by MBatt1** [comment]
Sliders are Aether IP and so we will not be making a slider dungeon since we are not allowed to use their ideas. Dungeons will be added but not a slider dungeon
