### ISSUE TITLE
Stuck on loading screen wih internal crash

### ISSUE THREAD

**Issue by GustavoJadson** [devs-immortal/The-Aether#403]
I can't create a new world, the loading screen is stuck on 1%.
Here's the MultiMC game log
[New Paste 1.txt](https://github.com/devs-immortal/The-Aether/files/6851641/New.Paste.1.txt)

**Comment by CDAGaming** [comment]
@GustavoJadson Use Fabric API 0.33 or below for the 1.16.5 version.
