### ISSUE TITLE
gravitite ore emits black dust particles

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#42]
![image](https://user-images.githubusercontent.com/53229958/100689691-92e4d980-334a-11eb-8c6c-9565cf3526d9.png)

**Comment by Hephaestus-Dev** [comment]
What's the expected behavior here? This is what sand blocks do. I can easily just remove the particles.

**Comment by MBatt1** [comment]
I mean it's not really sand but if anything having them pink and/or having them float up instead would be better
