### ISSUE TITLE
Boulder generation funk

### ISSUE THREAD

**Issue by Azzyypaaras** [devs-immortal/The-Aether#425]
They really do be spawning every chomk doe
![image](https://user-images.githubusercontent.com/20349662/126882216-bcacf945-4b8a-44b9-af52-840e098a7a04.png)

**Comment by CDAGaming** [comment]
Azzy wtf did you do to this world?!

**Comment by Azzyypaaras** [comment]
The boulders CDA, they whisper to me, they speak of walnuts.
