### ISSUE TITLE
Various mechanics should be delegated to external api

### ISSUE THREAD

**Issue by SollyW** [devs-immortal/The-Aether#429]
Various mechanics are implemented in ways that are either a maintainance burden, duplicate effort, or cause imcompatibilities with other mods. These should be changed to use external apis; however, many of these apis currently do not exist.
Feel free to add additional items to the list. Items marked with (*) already have an api in fapi or elsewhere

- [x] *Enchantment tables with skyroot bookshelves (particle effect, enchantment level increase) (in third-party mod)
- [ ] Skyroot buckets (fluids, milking)
- [x] Aether farmland (moisture, rabbits, villagers, plantable, etc.)
- [x] *Block colours
- [x] *Item colours
- [x] Glass pane and torch registering
- [x] Entity model layers
- [x] Falling leaf particles
- [ ] *Quicksand gamerule network packets (maybe change gamerule to config value?)
- [x] Item rarity
- [x] *Fuel times for aether items
- [x] *Strippable blocks
- [x] *Shovels flattening aether grass
- [x] Aether blocks added to ~~isSoil and~~ isStone checks in feature generation
- [x] *Item groups
- [ ] Simplex noise

**Comment by Azzyypaaras** [comment]
Damn you didn't need to murder CDA like that
![hmmmm](https://user-images.githubusercontent.com/20349662/126885979-11330908-8e41-4d6e-b59a-2bc174fcf09f.jpg)

**Comment by SollyW** [comment]
Well some of these are really bad - the enchantment table and rabbit, for example, will cause a crash if another mods adds their blocks

**Comment by Jack-Papel** [comment]
I believe gudenau has an API for the enchantment table and farmland, among other things we'd desire.

**Comment by Jack-Papel** [comment]
Bookshelves and Aether Farmland ✔️

**Comment by Jack-Papel** [comment]
Fuel, Pane, Torch, Particle ✔️

**Comment by Jack-Papel** [comment]
Color Provs, Item Groups ✔️

**Comment by Jack-Papel** [comment]
Only three to go ✔️

**Comment by Jack-Papel** [comment]
Do we think this is sufficiently complete?
