### ISSUE TITLE
gravitite ore acts a bit weird

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#43]
when gravitite falls upwards, after leaving render distance, and then coming back into range, falls a number of blocks before slowing down and then floating up again

Replicate by letting a gravitite float up, then fly up to it once it dissapears.

**Comment by CDAGaming** [comment]
While I couldn't reproduce this, another issue was located where _you can stand on floating gravitite too_

**Comment by MBatt1** [comment]
seems to be fixed idk
