### ISSUE TITLE
Blue Swets are feature deficient

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#439]
Blue Swets don't have anything going for them, except being "wet", which means just giving off particles.
~~It'd be cool if you could swim in them or something (nvm, way too difficult)~~, or if they put out fires.

**Comment by MBatt1** [comment]
They should take damage in the nether

**Comment by Azzyypaaras** [comment]
White ones should turn into vermillion ones

**Comment by CDAGaming** [comment]
Closing in favor of #543 (Stating a feature rather then a statement)
