### ISSUE TITLE
The error when starting minecraft. Multiplayer. Server.

### ISSUE THREAD

**Issue by DexGarden** [devs-immortal/The-Aether#447]
> _Well, English isn't my native language, but I try to discuss the problem._

I would like to start with the fact that we have installed the mod on our SMP, where there were only four people. 
In the result, **3/4 were able to go on playing with this mod**. However, our friend couldn't even start the game because of the constant **crashes of the program**. **He has reinstalled mods. Nothing.** We don't know what to do. 
### **Has anyone had the same problem?** 

> **We have had identical packs of mods, and we were playing tlauncher.**

**Comment by SollyW** [comment]
Hello.
Could you please send us the crash report from your friend's game? The location of the file depends on the launcher. You will need to find the location of the file with tlauncher. 
Also, if you can tell us your native language, we might be able to help you more.

**Comment by SweepSwap** [comment]
please consider purchasing minecraft for real instead of using tlauncher. Piracy= bad

**Comment by ghost** [comment]
Tell your friend to uninstall all mods they might have. On TLauncher: Go to the gear icon, Settings > TLauncher Settings > Full Reset. This should work, if it doesen't, send a crash log.

**Comment by DexGarden** [comment]
> please consider purchasing minecraft for real instead of using tlauncher. Piracy= bad
