### ISSUE TITLE
Client Crash when joining MP Server - Cannot read field "field_13073" because "â˜ƒ" is null

### ISSUE THREAD

**Issue by SHXRKIEgg** [devs-immortal/The-Aether#448]
Apologies if this is a Duplicate.

Client Crash when joining MP Server  with this error java.lang.NullPointerException: Cannot read field "field_13073" because "â˜ƒ" is null

1.17.1 latest Version in the [Medieval Minecraft Modpack](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric)

https://pastebin.com/DGFSVK8J

**Comment by Jack-Papel** [comment]
Please let the creator of the mod pack know. This seems like an issue on their end.
Multiplayer servers work fine for the aether, so it is an incompatibility with one of the other mods in the pack causing this.

**Comment by Jack-Papel** [comment]
If you're the creator of the mod pack, let us know

**Comment by thintheserverowner** [comment]
he is

**Comment by Jack-Papel** [comment]
@SharkieTV Does this issue occur on the latest version of our mod?

**Comment by SHXRKIEgg** [comment]
Not sure if its happening anymore as it just got released but I think this happens due to my players not having matching modpack versions. So it might not have anything to do with you.
