### ISSUE TITLE
[1.17.1] Ores can be mined with wood and stone pickaxe

### ISSUE THREAD

**Issue by kwpugh** [devs-immortal/The-Aether#452]
Hi,

Not sure if this is intended, but all three ores can be mined by wood and stone pickaxe.

Using latest Aether

WHIT also shows them as harvestable.

![2021-08-15_21 01 48](https://user-images.githubusercontent.com/8809210/129502371-f4522850-8d12-4ae4-a867-0e0062c8d47b.png)

**Comment by Jack-Papel** [comment]
I can't reproduce this bug. Can you send your full mod list?

**Comment by Jack-Papel** [comment]
If you could get back to us on this issue it'd be much appreciated

**Comment by kwpugh** [comment]
<img width="710" alt="Screen Shot 2021-09-04 at 6 50 01 PM" src="https://user-images.githubusercontent.com/8809210/132110598-c5ca2f45-27ea-47de-8443-49d1350f73cb.png">
<img width="710" alt="Screen Shot 2021-09-04 at 6 50 09 PM" src="https://user-images.githubusercontent.com/8809210/132110599-a6cf8621-6add-4a7e-adb9-8156bba85164.png">

**Comment by kwpugh** [comment]
This simple setup allows you to break ores with wood pickaxe

**Comment by Jack-Papel** [comment]
Thanks for getting back to us. It appears this bug has been fixed already in the latest dev build. Thanks for reporting!

**Comment by kwpugh** [comment]
no prob, just thought I'd mention it.   Swatting bugs in my own mods, sorry for the delay.
