### ISSUE TITLE
Mod conflict: Modern Industrialization lignite coal isn't a fuel when The Aether Reborn is installed

### ISSUE THREAD

**Issue by FreeFull** [devs-immortal/The-Aether#457]
**Describe the bug**
Normally, the lignite coal item from Modern Industrialization works as a fuel, but it doesn't if The Aether Reborn is also in the modpack.

**To Reproduce**
Add both Modern Industrialization and The Aether Reborn to a modpack.
Try to use lignite coal as a fuel (for example, in a furnace).

**Additional context**
Minecraft 1.17.1

Mod versions:
aether-1.17.1-1.5.0
architectury-2.4.26-fabric
cloth-config-5.0.38-fabric
fabric-api-0.39.1+1.17
RoughlyEnoughItems-6.0.268-alpha-fabric
Modern-Industrialization-0.5.10

**Comment by Technici4n** [comment]
You should probably be using fabric API's `FuelRegistry` instead of your `AbstractFurnaceBlockEntity` mixin, which unfortunately cancels fabric API's fuel hook (used by MI).

**Comment by Jack-Papel** [comment]
Thanks for letting us know. I'll make a fix
