### ISSUE TITLE
Axolotls do not survive the trip to the Aether

### ISSUE THREAD

**Issue by Lylythii** [devs-immortal/The-Aether#458]
**Describe the bug**
Creating an Aether portal with a Bucket of Axolotl (& in contrast, probably other buckets of entities), will delete the entity.

**To Reproduce**
Create a portal using a Bucket of [Entity]

**Expected behavior*]
Entity should teleport into the dimension, rather than disappear.

**Comment by Jack-Papel** [comment]
@kyrptonaught

**Comment by Jack-Papel** [comment]
Thanks for letting us know

**Comment by kyrptonaught** [comment]
Interesting, I'll investigate
