### ISSUE TITLE
BungeeCord Vanilla 1.16.5 cant join.

### ISSUE THREAD

**Issue by Lice2** [devs-immortal/The-Aether#459]
### **If your feature request is related to a problem:**
Hi.
I have the problem that when I have installed the Aether Mod I cannot join my lobby bungeecord server.
The BungeeCord Lobby Server runs on Spigot Version 1.16.5, with viaVersion.
With all other mods I can join the lobby server.
I currently have over 50 mods that don't cause any problems.
Can you see if something can be done there.

I use the Aether Mod Beta 1.5.0 for Minecraft 1.17.1

Kind regards

Lice

**Comment by Jack-Papel** [comment]
You can't use a mod made for 1.17 on a 1.16 server.
In the future, please use the bug report template instead of the feature template.
