### ISSUE TITLE
Incompatibility with immersive portals and colormatic

### ISSUE THREAD

**Issue by Snivyer1910** [devs-immortal/The-Aether#46]
As the title suggest the mod is incompatible with immersive portals, I think due to conflicting mixins between the aether portal and how immersive handles portals

https://paste.ee/p/WodUb

**Comment by Snivyer1910** [comment]
it's also incompatible with colormatic due to the aether not having a proper color palette

https://paste.ee/p/5Vttv

**Comment by Nathan22211** [comment]
I think the aether mod uses someone else's portal API, so that means it's likely an issue with that mod

**Comment by diabolical17** [comment]
Immersive portals will not work with any custom portal mods unless they implement it

**Comment by diabolical17** [comment]
Colormatic may be fixable, i'll have a look at it.

**Comment by Snivyer1910** [comment]
should I make a suggestion on Immersive Portal's side?

**Comment by diabolical17** [comment]
Yeah go ahead :)

**Comment by diabolical17** [comment]
Link https://github.com/kyrptonaught/custom-portal-api whilst you're at it.

**Comment by Jarfeh** [comment]
To quote quoteall
> The crash with aether is probably fixed in the next version.
About the custom portal API, I am not going to integrate with custom portal API. I am designing this mod's own portal API.

**Comment by qouteall** [comment]
To be clear, although I am not going to adapt to CustomPortalAPI, Immersive Portals provide custom datapack functionality for converting other mod's conventional portal into see-through portal https://github.com/qouteall/ImmersivePortalsMod/wiki/Datapack-Based-Custom-Portal-Generation

But the portal conversion functinality is not complete yet. I am going to add a new portal generation form. After completing that AetherReborn can simply add a json file and Immersive Portals will automatically convert the portal after player teleported once.

**Comment by qouteall** [comment]
You can use IP's datapack-based portal generation feature to make the portal be converted after the player teleports.
https://qouteall.fun/immptl/wiki/Datapack-Based-Custom-Portal-Generation

You need to put a json file in `data/the_aether/custom_portal_generation`, the json file's content is 
```
{
  "schema_version": "imm_ptl:v1",
  "from": ["minecraft:overworld"],"to": "the_aether:the_aether",
  "form": {"type": "imm_ptl:convert_conventional_portal","portal_block": "the_aether:blue_portal"},
  "trigger": {"type": "imm_ptl:conventional_dimension_change"}
}
```
(the json file's name doesn't matter)
The block id and dimension id may have typo

**Comment by MBatt1** [comment]
resolved in b1.0.3
