### ISSUE TITLE
Oranges always fall in the center of the block

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#467]
Randomtickspeed 1000
Weather rainy

![image](https://user-images.githubusercontent.com/64770632/131300598-d0d2ef9e-a7e2-461a-bf36-43bea7f333ed.png)

This also occurs with their particles, as you can see.

**Comment by RetroRusty13** [comment]
Can't figure out how github works, replace line 69 in blocks.natural.tree.FruitingLeavesBlock with:
ItemScatterer.spawn(world, pos, DefaultedList.ofSize(1, new ItemStack(fruit.get())));

**Comment by Jack-Papel** [comment]
Thank you very much @RowingRussell !

**Comment by Jack-Papel** [comment]
Resolved on b1.7 branch. Change needs to be ported to 1.18.2

**Comment by MBatt1** [comment]
Resolved on 1.18.2
