### ISSUE TITLE
Portal bugs in latest dev build

### ISSUE THREAD

**Issue by reoseah** [devs-immortal/The-Aether#468]
**Describe the bug**
- portal can be lighted without complete frame
- it doesn't need all blocks inside to be air, it just replaces them with portal blocks
- some other glowstone blocks can be moved with piston without breaking portal

**To Reproduce**
1. make a portal
2. depending on axis, either in positive Z or negative X direction blocks can be removed as in image
3. on other side blocks can be moved with pistons

**Expected behavior**
Portal without any block doesn't light up.  Also it shouldn't light up if any block within the frame is not an air or water. If there's a lit portal and any frame block gets destroyed, portal get destroyed. 

**Screenshots**
![2021-08-30_05 51 18](https://user-images.githubusercontent.com/20323084/131344598-2dfabebf-16b1-49c4-9c36-729b9d9d00e3.png)
![2021-08-30_05 45 45](https://user-images.githubusercontent.com/20323084/131344738-69a5a3cb-d79e-4127-a734-15dd8601b634.png)

![2021-08-30_05 53 48](https://user-images.githubusercontent.com/20323084/131344605-2e184377-c022-494a-ae74-bed113464014.png)
![2021-08-30_05 49 55](https://user-images.githubusercontent.com/20323084/131344608-76cc1eff-5057-4c1c-87b1-ac48b2ca0d7e.png)

**Additional context**
In latest dev environment (https://github.com/devs-immortal/The-Aether/commit/76df3de7a562dc868222f7b9af743884a75b579e)

**Comment by CDAGaming** [comment]
CC @kyrptonaught as this API is almost now entirely custom to CPI

**Comment by kyrptonaught** [comment]
This was fixed in beta 42, sorry about that!
