### ISSUE TITLE
Crash when wearing cape on server

### ISSUE THREAD

**Issue by notVigilant** [devs-immortal/The-Aether#470]
### What were you doing when the crash occured?

If a player equips a cape (any) into a trinket slot on a server, the game will crash for everyone on the server. UPDATE: If you put an elytra into a cape trinket slot the same thing happens.

### Did it crash the client or server?

Client

### Mod Version

b1.5.0 (1.17, Latest)

### Fabric API Version

fabric-api-0.39.2

### Trinkets Version

trinkets-3.0.3

### Crash Report

```shell
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class com.aether.items.accessories.ItemAccessory cannot be cast to class net.minecraft.class_1746 (com.aether.items.accessories.ItemAccessory is in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @5f9be66c)
Exit Code: -1
```

### Other mods

```shell
Better Minecraft V10 modpack and Origins 1.0.3
```

### Additional Information

We're running the CurseForge launcher, and the server is running on my PC with 9G available. The crash is reproducable 100% of the time and the only thing that stops everyone from crashing is using /kill on the player involved quickly upon joining before his game crashes.

**Comment by notVigilant** [comment]
Apologies for not putting a title, just made my GitHub account and I have no clue on how this site works.

**Comment by Jack-Papel** [comment]
That's alright, I'll add a title for you.
By the way, it looks like you've just sent the crash report preview. It'd be much appreciated if you could send the entire thing. The full crash report can be found in .minecraft/crash-reports, or by clicking the "View Crash Report" button on the "Game Crashed" popup.

**Comment by notVigilant** [comment]
[crash-2021-09-04_03.33.41-client.txt](https://github.com/devs-immortal/The-Aether/files/7109033/crash-2021-09-04_03.33.41-client.txt)
Here it is. I've also updated the post since equipping an Elytra into the cape trinket slots crashes the game as well.

**Comment by reoseah** [comment]
See https://github.com/KxmischesDomi/MoreBannerFeatures/issues/5

Apparently fixed in latest version of More Banner Features at https://www.curseforge.com/minecraft/mc-mods/more-banner-features/files/3447090
