### ISSUE TITLE
Bug: Cockatrice wing flapping

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#471]
### What happened?

After being attacked by an aechor plant, and for a while after the aechor plant is dead, cockatrices' wings will flap as if they're still in attack mode.

### Version

Dev

### Fabric API Version

dev

### Trinkets Version

dev

**Comment by CDAGaming** [comment]
Requires an Aechor Plant Target adjustment to resolve, further discussion required
