### ISSUE TITLE
Bug / mod compatibility: aether leaves / grass not waving with shader

### ISSUE THREAD

**Issue by TobiPeterG** [devs-immortal/The-Aether#478]
### What happened?

Hey there,

I'm using the aether mod with Iris and sildurs enahnced default shaders and I noticed that the leaves and grass is not waving in the wind. Such content added by other mods does, but these don't add a complete new dimension, 

Might it be possible to add shader support to this mod?

### Version

Dev

### Fabric API Version

0.40.0

### Trinkets Version

3.0.4

**Comment by Jack-Papel** [comment]
Hi. I've talked with an Iris developer, and unfortunately there is nothing we can do to fix this. Ask the creator of your shaderpack to add support for our mod. Thanks for reporting, and have fun in the Aether.
