### ISSUE TITLE
Bug: inconsistent overworld travel multiplier

### ISSUE THREAD

**Issue by slobodonmilosevic** [devs-immortal/The-Aether#480]
### What happened?

When entering the aether via glowstone portal my overworld coordinates are **divided by 10** to determine my aether coordinates. When dropping out of the aether by falling off an island my aether coordinates are **multiplied by 16** to determine my overworld coordinates. By iterating this process I was able to grow my coordinates exponentially, quickly reaching the world border.

### Version

1.5.0 (Latest)

### Fabric API Version

0.37.2

### Trinkets Version

3.0.2

**Comment by Jack-Papel** [comment]
Thanks for reporting. This has been fixed in the latest dev version, and will be in the next update. Have fun!

**Comment by Azzyypaaras** [comment]
Resolved with b1.6.0
