### ISSUE TITLE
Bug: Mod Conflict: Teeny Coal's items are not being added to the FuelRegistry

### ISSUE THREAD

**Issue by Andrew6rant** [devs-immortal/The-Aether#481]
### What happened?

Whenever Teeny Coal and Aether Reborn are ran together, Teeny Coal's items do not get added to the FuelRegistry and thus cannot be placed into furnaces.

Here is a link to Teeny Coal: https://github.com/Andrew6rant/Teeny-Coal

I am the developer of Teeny Coal and can try to assist in any mod-compatibility efforts.

### Version

1.5.0 (Latest)

### Fabric API Version

0.40.1+1.17

### Trinkets Version

3.0.4

### Other mods

None

**Comment by Jack-Papel** [comment]
Thanks for reporting this. This is an issue with the latest release, and has been fixed in dev builds. Also thanks for the offer. If you have any more incompatibilities in the future please let us know.

**Comment by Azzyypaaras** [comment]
Resolved with b1.6.0
