### ISSUE TITLE
Giant's Leaf pad collision

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#482]
Walking into a giant's leaf pad from the side stops the player, just like a lily pad. walking in from the corner makes the player crawl (or, swim).
You can't hit a giant's leaf lily pad from the sides.
You can place blocks where the giant lily pad is (not in the center, but on the sides.)

**Comment by MBatt1** [comment]
Giant lily pad is soon to be removed. Closing
