### ISSUE TITLE
Flying Structures

### ISSUE THREAD

**Issue by Mcboyo** [devs-immortal/The-Aether#491]
### What happened?

I was in Creative mode and noticed the structures generating on the Aether are flying. For example: villages would spawn beside the islands with no floors, same as the towers.

### Version

1.4.1 (1.16)

### Fabric API Version

0.11.6

### Trinkets Version

2.6.7

**Comment by Jack-Papel** [comment]
Please share your mod list

**Comment by Jack-Papel** [comment]
Please share your mod list

**Comment by Mcboyo** [comment]
> Please share your mod list

Hmm, it appears I forgot about this. Unfortunately this was 2 months ago and the mod list I have is different to the one I had then and I'm no longer using Aether Reborn in my modpack. However, I do faintly remember uninstalling mods and the issue went away, but I don't know what they were. Sorry for the inconvenience.

**Comment by Jack-Papel** [comment]
Oh well. Thanks for getting back to us eventually.
