### ISSUE TITLE
Bug: Golden Aercloud instantly kills the player

### ISSUE THREAD

**Issue by Greenknight9000** [devs-immortal/The-Aether#493]
### What happened?

Touching Golden Aercloud will shoot you down to the ground at a fatal speed, rather than shooting you upwards into the air  - I see this having potential being a feature as a new variant of Aercloud, but obviously, the Golden Aercloud is meant to launch you upwards into the air
![image](https://user-images.githubusercontent.com/91160044/134247422-9be8c739-f3fe-4aab-80cc-0da347cafeb1.png)
![image](https://user-images.githubusercontent.com/91160044/134247530-69e2e8ef-2cde-4057-9c2c-c132b01d9dd6.png)

### Version

1.5.0 (Latest)

**Comment by Jack-Papel** [comment]
The blue aercloud launches you into the air
