### ISSUE TITLE
Bug: Can't launch 1.5

### ISSUE THREAD

**Issue by itsdinkd** [devs-immortal/The-Aether#506]
### What happened?

when launching game, it crashes. error in log 

https://pastebin.com/5sXPmPd9

something to do with mixins 

### Version

1.5.0

**Comment by itsdinkd** [comment]
Another crash log https://pastebin.com/EmFWQd47

**Comment by Jack-Papel** [comment]
The first issue is a known conflict with ExpandAbility, which will get resolved.
The second issue is unrelated, and seems to be due to CustomPortalAPI. I'll ping @kyrptonaught so he can see this

**Comment by kyrptonaught** [comment]
The release of 1.5.0 used an older version of CPA, and an older method of fluid portal ignition. This older method was reworked and is no longer present in never CPA, such as beta-45 which is installed here from another source. The dev versions have been updated to reflect this change and it's no longer an issue.

**Comment by frikinjay** [comment]
Had a similar crash with 1.6.0 and I am not using ExpandAbility, not sure if its the similar issues you mentioned.
https://pastebin.com/Tq9da7BE

Edit: the crash happens on 1.5.0 as well and is identical.

**Comment by Jack-Papel** [comment]
@frikinjay The crash report you sent shows that you are indeed using ExpandAbility

**Comment by frikinjay** [comment]
I see, could be one of the mod's including it in the jar, man do I hate that. Any way to check what mod might be using it as a dependency instead of manually checking it?

**Comment by Jack-Papel** [comment]
I believe you'll have to check manually

**Comment by frikinjay** [comment]
Well that didnt take as long as I thought it would. [Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric) includes expandability. Thanks for the help.

**Comment by CDAGaming** [comment]
Closing as long-been-resolved.
