### ISSUE TITLE
Bug [1.6.0-Beta / Latest commit 10/14/21] Crash on start up

### ISSUE THREAD

**Issue by itsdinkd** [devs-immortal/The-Aether#509]
### What happened?

Loading 1.5.0 works fine, but when trying to use 1.6.0, I crash on startup. With Not Enough Crashes, it first blamed Iris on a null value for getPipeLine(), which Iris said is impossible. 

I then switched from NEC to Crafty-Crashes, and its giving me a completely different error, which looks more realistic. 

https://pastebin.com/x9BS4jPM 
Mining Dims uses CustomPortalAp

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.size()" because "c" is null
	at java.base/java.util.HashSet.<init>(HashSet.java:120)
	at net.minecraft.class_2591.handler$gga000$makeBlocksMutable(net/id/aether/mixin/block/BlockEntityTypeMixin.java [the_aether.mixins.json]:25)
```

When I disable Torcherino, I get this error, which gives us some more info on CPApi, MiningDims(which uses CPApi)

https://pastebin.com/2nZeZ3ts

### Version

Dev

**Comment by itsdinkd** [comment]
Updating Mining Dims to latest version, which uses the latest CPA fixes this. Torcherino is still disabled though.

**Comment by itsdinkd** [comment]
After updating to mining dims, this fixes problem.

**Comment by Azzyypaaras** [comment]
Resolved with b1.6.0
