### ISSUE TITLE
Incompatibility with Glided Netherite (possibly more armor/tools mods)

### ISSUE THREAD

**Issue by Snivyer1910** [devs-immortal/The-Aether#51]
Seems that the aether fails to load the render of the Glinded Netherite armor

anywho here's the crash report

https://paste.ee/p/CF9OT

**Comment by Snivyer1910** [comment]
grammar

**Comment by diabolical17** [comment]
The Aether has nothing to do with gilded netherite? Go give this to the gilded netherite developer.

**Comment by diabolical17** [comment]
Sorry for being passive agressive 😅 Its actually a geckolib problem, we use it to render our armor. Could you report more infomation on the issue on geckolib issue?

https://github.com/bernie-g/geckolib/issues/49

**Comment by Snivyer1910** [comment]
should I make an issue with this on geckolib's and glided netherite's github?

**Comment by IMS212** [comment]
I don't believe an issue should be made on Gilded Netherite's github, as this error seems to affect a lot more stuff than just Gilded Netherite, and it's not their problem in any way.
