### ISSUE TITLE
Bug: Confliction with Artifacts -- Mixins conflicting

### ISSUE THREAD

**Issue by itsdinkd** [devs-immortal/The-Aether#512]
### What happened?

Server crashes upon starting, gives a message about mixin conflictions with Aritfacts (Tried both 5.0.2, 5.0.0, already reported to Artifacts Dev) 

Here is the log

https://pastebin.com/U67j75qc

### Version

Dev

**Comment by itsdinkd** [comment]
reported to artifacts https://github.com/florensie/artifacts-fabric/issues/47

**Comment by Jack-Papel** [comment]
This has been reported already. (#497) Thanks for letting us know, though. This bug will be worked on
