### ISSUE TITLE
Saplings Do Not Stack

### ISSUE THREAD

**Issue by CH1KNTenders** [devs-immortal/The-Aether#519]
### Problem

I broke 1 Tree and somehow got like 30 saplings, and my magnet sucked ALL of them to me, there were more orbiting me that haven't even been picked up yet.
![2021-10-30_23 52 21](https://user-images.githubusercontent.com/93461538/139568394-1f9bf233-ea38-4078-9147-02f6612a06d1.png)
![2021-10-30_23 52 53](https://user-images.githubusercontent.com/93461538/139568395-35fdfc22-fbe4-4775-abdd-090b9265593f.png)

### Feature

You Should Let Saplings Stack.

### Other Solutions

You Could Also Make Them Drop Less Saplings.

### Version

Unsure

### Additional Information

Its in a mixed modpack of 316 mods, none of them, I believe cause only Aether Saplings not to stack, but who knows.
![2021-10-30_23 57 05](https://user-images.githubusercontent.com/93461538/139568490-bd713ef8-0b8f-449e-a5e1-f8bc0aff2124.png)

**Comment by Jack-Papel** [comment]
Please send a list of your mods. Our saplings don't do this with just our mod installed.

**Comment by Jack-Papel** [comment]
Please send a list of your mods.

**Comment by Jack-Papel** [comment]
Closing as abandoned
