### ISSUE TITLE
Floating Blocks are entirely broken

### ISSUE THREAD

**Issue by Fishiest** [devs-immortal/The-Aether#523]
You can break bedrock, get infinite food, and hold farmland
https://youtu.be/BSPIq1fID8U

**Comment by Jack-Papel** [comment]
This has been fixed in dev builds. Thanks for reporting. Let us know if you find any more bugs.

**Comment by Jack-Papel** [comment]
Actually, I just watched the video and I wasn't aware of the piston thing. I'll double check that we fixed that. I appreciate the dramatic zooms too.

**Comment by Jack-Papel** [comment]
Alright, now the problem is fixed 👍🏻

**Comment by Azzyypaaras** [comment]
Resolved with b1.6.0
