### ISSUE TITLE
Bug: For some reason there are no structures and only slimes.

### ISSUE THREAD

**Issue by Lampstern** [devs-immortal/The-Aether#524]
### What happened?

I can still summon all the mobs and see the gear and stuff, but I have no way to get the stuff in survival.
I feel like there is a super simple fix to this, but I can't find the problem.

### Version

1.5.0 (Latest)

### Fabric API Version

1.17.1 0.42.0

### Trinkets Version

1.17.1 3.0.4

### Other mods

```shell
architectury
bclib
better-end
better-nether
dawn
eating-animation
extraorigins
origins
origins-classes
fabric-api
iris-and-sodium
litematica-fabric
lithium-fabric
logical-zoom
malilib-fabric
modmenu
mostructures
pehkui
promenade
RoughlyEnoughItems
trinkets
```

### Additional Information

I barely have any idea what I am doing

**Comment by Jack-Papel** [comment]
The mod is in beta, so 1.5.0 doesn't have everything yet. The next update, 1.6.0, will expand what is there. Hope this answers your question.
