### ISSUE TITLE
Bug: Falling from the aether can place you outside the world border

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#525]
We should probably have it follow whatever is done for portals.

**Comment by gudenau** [comment]
Shouldn't this be handled in the custom portal API since the teleportation logic should be there and not in the Aether?

**Comment by kyrptonaught** [comment]
Yes, I have fixed the portals in CPA. I also fixed the falling here in the aether. See: 4184e30ec752ecd7cf1d11d39165d825544fca0f

**Comment by Azzyypaaras** [comment]
Resolved with b1.6.0
