### ISSUE TITLE
[Bugs] (list of everything I've found)

### ISSUE THREAD

**Issue by SylisMC** [devs-immortal/The-Aether#53]
First and foremost, I love the mod and I love what you are doing! I am by no means trying to criticize, I understand the mod is in beta and is prone to bugs, I'm just listing my finding, Bugs, or behaviors I think might be unintentional. Thanks for all the hard work. I really hope this project continues

**Misc**
    - Setting tick speed to 1000 can crash the game easily (in aether)
    - Bees spawn in the aether
    - Blueberry bushes don't drop bush when broken by hand, with shears, or silk
    - Blueberry bushes are immune to water/lava
    - Gravetite tools don't effect gravity (WIP i assume)
    - Gravetite ore flings up and down through the sky violently until eventually breaking (used to just soar into the sky and disappear, is this intentional?)
    - Portals are not generated in the same shape as built (if build outside of a 2x3) and dont send you back to the original portal (creates a new 2x3 in the overworld)

**Trees/wood**
    - Leaves are immune to fire
    - Logs and wood are immune to fire
    - Saplings don't drop from leaves
    - Leaves don't decay (excluding sky root) (couldn't test crystal)
    - Crystal saplings grow into nothing (appear to leave a ghost block in its place)
    - Crystal saplings cause crash on growth with tickspeed set high (can still load into the world after reboot)
    - Stripped logs cause decay (differs from vanilla)
    - Fences don't link to each other (tested walls, they work fine)

**Water**
    - All waterloggable blocks waterlogged without any problems! (excluding fence gates but that's the same as vanilla)
    - Leaf piles are immune to water/lava
    - Hangerplants are immune to water/lava
    - Blueberry bushes are immune to water/lava
    - Trees that grow with the random tick speed set higher spawn deformed almost as if the leaves are spawning before the logs, and then despawning because there are no logs(yet)

**Quicksoil**
    - Works with blocks above quicksoil up to five snowlayers (carpet, slabs, rails, snow (up to five layers)
    - Not on beds(4 layers) for some reason
    - Boats on quicksoil can crash game
    - Boats on quicksoil can cause the player to keep spinning after getting out (only happened to me once)
    - [idea] Quicksoil boosting minecarts (might be a practical usage for quick soil)

**Creative Tab** _(doesn't effect game, just an OCD thing)_

    - Holystone, Mossy Holystone & Holystone bricks are separated from its part block counterparts (slabs stairs, walls)
    - hellfire walls appear before slabs and stairs,

**Comment by kalucky0** [comment]
> Portals are not generated in the same shape as built (if build outside of a 2x3) and dont send you back to the original portal (creates a new 2x3 in the overworld)

I think that might be a problem with @kyrptonaught's CustomPortalApi rather than with the Aether code. The rest should be easily fixable. Btw, next time try to make separate issue for every bug, it will make managing them a lot easier.

**Comment by diabolical17** [comment]
Actually, please can you seperate each bug into a seperate issue?

**Comment by diabolical17** [comment]
I can help with it dw, i'll get started seperating for you.

**Comment by diabolical17** [comment]
Crystal Saplings aren't implemented yet.

**Comment by diabolical17** [comment]
Going to close for now, i made issues for all the bugs you have found that are not reported.

**Comment by SylisMC** [comment]
i can do it it will just have to be later today
