### ISSUE TITLE
Bug: server can't launch with bclib

### ISSUE THREAD

**Issue by Dreeam-qwq** [devs-immortal/The-Aether#538]
### What happened?

Server can't launch with aether and bclib(the dependency of better nether and better end)

### Version

Dev

### Fabric API Version

0.42.1

### Trinkets Version

3.0.4

### Relevant log output

```shell
https://paste.gg/p/anonymous/5673e581ed6445a1bb5c645fc726015a
```

### Other mods

```shell
geckolib-fabric-1.17-3.0.26
bclib-0.5.1
```

**Comment by Jack-Papel** [comment]
@gudenau looks like an issue with the recipe dependency

**Comment by gudenau** [comment]
This isn't on me, they are overriding a method.

https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/common/RecipeManagerMixin.java#L36
