### ISSUE TITLE
modrinth update

### ISSUE THREAD

**Issue by lostopkk** [devs-immortal/The-Aether#554]
modrinth is the lastest version beta 1.4.1 please update to a new versions

**Comment by Jack-Papel** [comment]
@Azazelthedemonlord

**Comment by Jack-Papel** [comment]
Mostly resolved. Modrinth now has 1.6.0, though not anything newer just yet

**Comment by Jack-Papel** [comment]
Modrinth now has 1.6.7. Thanks for reporting.
