### ISSUE TITLE
Bug: Console Spam

### ISSUE THREAD

**Issue by xanthian** [devs-immortal/The-Aether#555]
### What happened?

![image](https://user-images.githubusercontent.com/7688001/143913118-4dc93c18-1644-4ced-8ed9-78d0b23110b5.png)
MC 1.17.1 
Fabric 0.12.5
AR Beta 1.6.2

### Version

Unsure

### Fabric API Version

0.43.1

### Trinkets Version

NA

### Other mods

![image](https://user-images.githubusercontent.com/7688001/143913410-65ea7028-4019-40ec-b430-c22d43fe5dcd.png)

**Comment by CDAGaming** [comment]
Resolved in b1.6.3
