### ISSUE TITLE
Crash: Poison Needle corrupts chunk

### ISSUE THREAD

**Issue by itsdinkd** [devs-immortal/The-Aether#565]
### What were you doing when the crash occured?

Not my report, a player of my modpack reported this to me. him and his friends if they go near a aether portal they immediately crash.

### Did it crash the client or server?

Client

### Mod Version

1.6.3.1 (Latest)

### Fabric API Version

43.1

### Crash Report

```shell
https://paste.corebot.dev/uredoqoyun.coffeescript
```

**Comment by RedThunderG** [comment]
I am having the same issue https://paste-bin.xyz/29376

**Comment by Jack-Papel** [comment]
This has been fixed in development versions, and should be all good to go in the next release. Thanks for reporting!

**Comment by Jack-Papel** [comment]
This has been fixed in 1.6.5+
