### ISSUE TITLE
Crash: Mixin conflict with ServerCore

### ISSUE THREAD

**Issue by Oliver-makes-code** [devs-immortal/The-Aether#569]
### What were you doing when the crash occured?

I added this mod to my server, and it crashed due to a mixin conflict with [ServerCore](https://modrinth.com/mod/servercore)

### Did it crash the client or server?

Not sure

### Mod Version

Dev

### Fabric API Version

0.45.2

### Trinkets Version

3.1.0

### Crash Report

```shell
https://pastebin.com/aSMxkNHV
```

### Other mods

```shell
ServerCore
Create Refabricated
```

**Comment by Jack-Papel** [comment]
Thanks for reporting this. This is a known bug. Funnily enough, the team was just discussing ways to fix it a few minutes ago. Be assured It's on our docket. Sorry for the inconvenience, and thanks for letting us know!

**Comment by Wesley1808** [comment]
Just so you know, I did already add a workaround that disables that specific patch conflicting on my end when this mod is installed (this in the development builds) - In case its a large struggle to replace that code with other mixin injectors.

**Comment by Jack-Papel** [comment]
Thanks Oliver - we just got this fixed. Seeing as how you're used to using dev versions, you'll be glad to hear we have a release candidate coming tonight with the fix in it tonight. The release itself is coming on the 14th. Thanks for reporting!

**Comment by Jack-Papel** [comment]
Closing as duplicate and resolved
