### ISSUE TITLE
Configurable counterpart to falling from the Aether into the Overworld: Flying from the Overworld to the Aether

### ISSUE THREAD

**Issue by NathanDreamweaver** [devs-immortal/The-Aether#571]
### Feature

There is currently a way to fall down from the Aether into the Overworld but not the opposite.
Why would one want to do the opposite, when they could just build a portal really high up that would be incredibly more efficient than flying all the way up to the Aether? Because it would be amazing used together with other mods!
In particular, I am thinking of the Create mod, since it is getting a Fabric port over at https://github.com/Fabricators-of-Create/Create. Just imagine it, an elevator all the way to the Aether!
There IS the issue of "where would one land upon reaching the Aether". I was thinking perhaps some sort of 3x3 clouds that appear at the bottom of the Aether where you spawn and vanish when you get slightly far away from them? After all, if someone managed to get there in the first place, they should be able to get to the islands too.

### Version

Dev

**Comment by CDAGaming** [comment]
The problem I see with this is...well two things:

1) The idea fails because one would expect to *see* the aether as they build up to it. We cant put the existing solution in reverse as thats going to break immersion (Unlike falling down  where you fall from such a distance that the world below isnt in render distance.)
2) If we try to acheive 1 via a similar solution another mod did (Cant remember the name but it allowed stacking dimension), its going to cause performance issues, so its then a matter of performance vs immersion/quality.

**Comment by CDAGaming** [comment]
As for the clouds solution you proposed, thats gonna be more then 600 blocks built up, more with mods installed or if the world is modified. Maybe there is an optimal solution for this, but Im personally unsure what that could be for good immersion and what would make a playable mechanic

**Comment by NathanDreamweaver** [comment]
Could be made toggle able in config, along with Y coordinate for it to happen. if one wants it then they don't care about immersion to that level

**Comment by Azzyypaaras** [comment]
HAYO
It's ya boy, the cum salesman, and also the lead designer.

Past what CDA has noted there are quite a few other reasons why this would not really work. The Aether is canonically not a few hundred over even a few thousand blocks above the overworld, but a few _tens of thousands,_ for this to make sense the buildable area of the world would need to be ridiculously tall.
Furthermore, when looking at things from a technical standpoint, trying to do this would bring up a lot of issues, dimension scaling comes to mind as the aether's coordinate scale is 10:1 with the overworld, how would this affect rendering and where you end up when building up? And past that even, actually getting the player to be able to smoothly go in and out of the aether like this would be exceedingly janky. 
A good place to look at for difficulty is immersive portals (which is the mod cda was thinking of), which is notably one of the most technically complex mods in the entirety of fabric modding, this would pretty much require us to replicate it.

It is simply the case that trying to implement thing wouldn't just not be worth the effort, but it would also likely result in copious breakage and hard to maintain code.

**Comment by Jack-Papel** [comment]
Lead developer here. I think this is a great idea, but it wouldn't really be feasible to execute, as the others have said. Even though we won't be able to do this idea, I'll be excited to hear any other ideas you might have in the future! Thanks for contributing, we really appreciate it.

**Comment by CDAGaming** [comment]
Id say in summary: The closest youll get with this is the dimension stacking properties of Immersive Portals, which even then has a wide array of unforseen issues that can occur. While its a good idea, theres a lot of complications that prevent a smooth execution.

**Comment by NathanDreamweaver** [comment]
For an alternate way to do the elevator to the Aether, should I put the idea here or in another issue?
Namely, horizontal portals

**Comment by Jack-Papel** [comment]
You can put it here

**Comment by Jack-Papel** [comment]
Closed as abandoned
