### ISSUE TITLE
Bug: Grass generation in ground

### ISSUE THREAD

**Issue by Aquaeyes** [devs-immortal/The-Aether#574]
### What happened?

Grass can still clip into ground near edges.

Example:
Seed: -6402812678833605992
XYZ: -21, 69, 51

![image](https://user-images.githubusercontent.com/10935410/149650632-0b405a65-6fdf-4b3d-9a1f-73ca877a0425.png)

### Version

Dev

### Fabric API Version

0.12.12

### Trinkets Version

3.1.0

**Comment by Jack-Papel** [comment]
Thanks for letting us know

**Comment by CDAGaming** [comment]
Resolved, closing as dev issue
