### ISSUE TITLE
Outdated strings in the Aether Crowdin Project

### ISSUE THREAD

**Issue by CapoFantasma97** [devs-immortal/The-Aether#582]
### Problem

In the [Aether Crowdin Project](https://crowdin.com/translate/aether/) for translations, it appears that the provided strings are obsolete.
Some of the items seem to not exist anymore, others, like the Light Carved Stone, have been updated to be Lit Carved Stone in the mod, but not in the localization strings.

### Feature

An upload of the updated en_us.json file seems to be required.

### Other Solutions

You could move up the translations efforts directly into this Github (pull requests of localization files). The problem with this however is how much more convoluted it is for a mod of this size to update translations. A place like Crowdin is still required in order to more easily handle, discuss and correct the large amount of strings involved.

### Version

1.6.3.1 (Latest)

**Comment by Jack-Papel** [comment]
Thanks for letting us know. This is on our radar. We're mostly focused on the 1.18 update, but afterwards I plan to hopefully trim up these files and for us to figure out a path forward with translations

**Comment by comradekingu** [comment]
@Jack-Papel
Happy to help if you use Weblate :)

**Comment by Jack-Papel** [comment]
We've updated the strings. Thanks for letting us know. Have fun with the mod!
