### ISSUE TITLE
Ideas from Aether Ascension

### ISSUE THREAD

**Issue by TheGag96** [devs-immortal/The-Aether#584]
### Feature

Some time ago, I made a fork of Aether I called "Aether Ascension". It's got a number of improvements over the base mod. I made a [pull request](https://github.com/Gilded-Games/The-Aether-Archived/pull/69) encouraging the dev team to incorporate at least some of the obviously fitting changes/fixes, but I never got any response. 

Not sure how much code could easily be ported over given this was a 1.12.2 Forge mod. I still wanted to at least bring this to your attention in the hope that some value could be gotten out of this, if it interests you all. 

Thanks for trying to keep the dream of a modern Aether alive!!

### Version

Unsure

**Comment by Jack-Papel** [comment]
Right now we're kind of locked in 1.18 update mode, but when we've completed that, we will check this out. Thanks for the suggestions!

**Comment by MBatt1** [comment]
I reviewed the changes from Aether Ascensions and we actually have implemented many of the changes, and several are very far out if even on our roadmap (ie no sheepuffs ever, and valkyries are far future plans), so while we appreciate the ideas, we have most of them covered already, so I may close this issue for now
