### ISSUE TITLE
Bug: Running Paradise Lost with Architectury causes unusually high GPU usage.

### ISSUE THREAD

**Issue by TheGrimsey** [devs-immortal/The-Aether#591]
### What happened?

When running the latest dev build (branch 1.18) with Architectury API the game will run at 100% GPU usage. Removing either Architectury or Paradise Lost fixes the issue.

With Architectury:
![FullGPU](https://user-images.githubusercontent.com/9167223/151994898-8f12aecc-850d-49ab-9dbb-f744ed1c44f6.JPG)
Without Architectury:
![NotFullGPU](https://user-images.githubusercontent.com/9167223/151995460-c0b756d9-26dd-4da1-b189-84f30f8c040f.JPG)

Aditionally here is the full log to show no other mod is present.
[latest.log](https://github.com/devs-immortal/Paradise-Lost/files/7979535/latest.log)

### Version

Dev

### Fabric API Version

0.46.1

### Other mods

```shell
Architectury 3.6.14
```

### Additional Information

Testing done in CurseForge launcher. Paradise Lost build grabbed directly from Github Actions.

**Comment by CDAGaming** [comment]
Using Architectury v3.6.16 and the latest action build on 1.18, GPU usage topped out for me at 40-50%, nearly the same as without. Suggesting a re-test when b1.6.4 releases or sooner if possible

**Comment by CDAGaming** [comment]
@TheGrimsey See #594 (Closing as resolved). This should be resolved now, but please ping me here if it isnt.
