### ISSUE TITLE
Feature: Bonemeal Wisteria Leaves + hitbox alignment

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#596]
Bonemealing wisteria leaves should generate a hanger. Bonemealing those hangers should grow them further.

Also the hitbox for wisteria hangers is not aligned to the model, which is annoying

**Comment by Jack-Papel** [comment]
Resolved on b1.7 branch. Change needs to be ported to 1.18.2

**Comment by MBatt1** [comment]
Resolved on 1.18.2

**Comment by Jack-Papel** [comment]
I know the bonemealing was added, but were the hitboxes adjusted?
