### ISSUE TITLE
Crash: biome makeover incompatibility

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [devs-immortal/The-Aether#598]
### What happened?
Crash on startup

### Mod Version

1.6.5 - 1.18

### Fabric API Version

newest from 1.18.1

### Relevant log output

```shell
https://drive.google.com/drive/folders/1N8iU-z2jo2RnxmtUOfdmd-flecaiX8k7?usp=sharing
```

### Other mods

Biome makeover 1.4.5 among others

**Comment by CDAGaming** [comment]
Assigned gud, as this is a moretags compatibility issue
