### ISSUE TITLE
Crash: Ticking entity - BlueSwetEntity [Latest 1.18 Beta]

### ISSUE THREAD

**Issue by SHXRKIEgg** [devs-immortal/The-Aether#603]
### What were you doing when the crash occured? How can we replicate it?

1. Create a server with fabric loader 0.13.2
2. Put fabric-api-0.46.4+1.18 and paradise-lost-1.6.5.1+1.18.1 in mods folder
3. Launch Server and enter The Aether then Crash

### Did it crash the client or server?

Server

### Mod Version

1.6.5 - 1.18

### Fabric API Version

fabric-api-0.46.4+1.18

### Crash Report

```shell
https://pastebin.com/RaCTBjuc
```

### Other mods

None

### Additional Information

Was first trying to add this to my Better Minecraft Modpack and it crashes server side so tested standalone and still crashes when entering the Dimension

**Comment by Jack-Papel** [comment]
Thanks for reporting! This issue has been fixed in 1.6.5.2. Have fun!

**Comment by SHXRKIEgg** [comment]
When will this be uploaded to Curseforge?

**Comment by Jack-Papel** [comment]
I'll let people know it's not on there yet. It should be up by tomorrow at the latest.

**Comment by Jack-Papel** [comment]
It's up now. Thanks for waiting

**Comment by gudenau** [comment]
My bad, it was my code that broke this.
