### ISSUE TITLE
Bug: contains other mods inside the jar

### ISSUE THREAD

**Issue by SubBastion** [devs-immortal/The-Aether#605]
### What happened?

A bug!

To replicate:
1. open jar
2. notice copyright infringement yay!

### Mod Version

1.6.5 - 1.18

**Comment by Jack-Papel** [comment]
Hey mate, I can see where your confusion stems from. This practice isn't disallowed nor looked down upon. If you look in our mod files on GitHub, we don't contain code for other mods. However, in our build.gradle, we include some library mods that help us with compatibility, among other things. For example, Incubus Core is an in-house mod intended to let all of our projects work together. If you look at the GitHubs of the mods that are included, you'll see that some of them even encourage the practice for ease of compatibility.
However, thanks for reporting anyway. We take copyright very seriously and we certainly don't want to put ourselves in a position where we are unfairly using the work of others.
I see that your report comes from a place of good heart. So thank you. And have fun with the mod, if you wish to!

**Comment by SubBastion** [comment]
there is literal jar files inside of your jar look again. I don't think you meant to do it or didn't know you could compile without embedding them as soft deps but that's what happened. I am a fan of the original aether but your redistributing other people’s mods in each version of yours

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Jack-Papel** [comment]
I suggest checking out the [Cardinal Components](https://github.com/OnyxStudios/Cardinal-Components-API#adding-the-api-to-your-buildscript) GitHub page for adding this mod as a dependency.
As you can see, it suggests and approves of the use of jar-in-jar inclusion - the very thing you are referring to. Jar-in-jar means it adds the mod's jar inside our own, hence the term.
We really do appreciate your concerns, however there is nothing to worry about.

**Comment by Azazelthedemonlord** [comment]
I suggest touching grass

**Comment by SubBastion** [comment]
There is many issues with your last statement. Jar in jar loader welp you just replaced any classes from the mods you depend upon if they loaded before you. Your classes will not override theirs essentially enforcing the mod you support is on the version you support. Another issue is file size your not suppose to have jars inside of your mod if it’s not a library. It makes your files huge. Another reason even if other mods are ok with it you shouldn’t redistribute their mod inside of your mod or vise versa.  Imagine now that someone depended upon your mod and that mod had 5 more jars your now going into the GB

**Comment by gudenau** [comment]
A few MB isn't going to add up to GB without some tomfoolery. This is standard practice and Fabric is designed with this in mind. The latest version of included mods will be used and we are not overriding any classes. Plus the mods are using open source licenses, allowing this use case.

**Comment by Jack-Papel** [comment]
We haven't had any compatibility issues so far 🤷‍♀️. We appreciate your concerns, but they don't seem to be based in any actual observable issues.

**Comment by SubBastion** [comment]
It’s not a few mb it’s 100mb with yours alone 10 mods later it will be gb. This also slows down loadtime. Your doing things wrong use fabric’s proxy if they provide one if they don’t report and issue. It’s what proxies were for

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gudenau** [comment]
It doesn't slow it down much and most of the file size comes from assets. I will admit that it makes mods a little larger, but the included mods just don't add too much compared to all of the images and audio files.

**Comment by Jack-Papel** [comment]
SubBastion was blocked for trolling. Anyone viewing this issue in the future should be aware that we value suggestions from our community. But being a brand new account created moments before this issue, as well as being dismissive and stubborn with their responses, we can only ascertain that this account is a troll
