### ISSUE TITLE
TODO: Replace CSL With Satan

### ISSUE THREAD

**Issue by gudenau** [devs-immortal/The-Aether#606]
CSL was rejected from Modrinth and CurseForge and does the same thing as CSL with wider support. CSL should be removed in favor of Satin.

**Comment by SollyW** [comment]
Why not drop it entirely? Sar has an example of adding a shader without anything in the middle

**Comment by Jack-Papel** [comment]
We had compatibility issues. I think the mod was called DashLoader

**Comment by Azzyypaaras** [comment]
1) Sar?
2) I do love me some _satan_

**Comment by Jack-Papel** [comment]
@Azazelthedemonlord SAR is Some Assembly Required. The library for the Artisanry and Skewer stuff

**Comment by Azzyypaaras** [comment]
Oh, right
