### ISSUE TITLE
Bug: Moa Subtitles display incorrectly

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#610]
Moa Subtitles are displayed as "Parrot Talks" and "Phantom Flaps", for example.

**Comment by CDAGaming** [comment]
This is due to the fact that it is in fact using those sounds, so this is more of a TODO that we need to give moa's (And other mobs) their own sound effects.

**Comment by Jack-Papel** [comment]
I think I fixed this.
