### ISSUE TITLE
Bug: Liverwort Unobtainable Through Mining

### ISSUE THREAD

**Issue by OdessaCubbage** [devs-immortal/The-Aether#611]
### What happened?

Don't know if this is intended or already known about, but right now it seems to be impossible for a survival player to obtain liverwort. Have tried shears, axe, hoe, shovel, pick, sword, & silk touch and all simply break the block while leaving nothing behind.

### Mod Version

1.6.5 - 1.18

### Fabric API Version

0.13.3

**Comment by Jack-Papel** [comment]
Resolved on b1.7 branch. Change needs to be ported to 1.18.2 branch

**Comment by MBatt1** [comment]
Resolved on 1.18.2, plus recipe for crafting liverwort carpets

**Comment by Jack-Papel** [comment]
Resolved in latest release
