### ISSUE TITLE
Portal not working!!!

### ISSUE THREAD

**Issue by RailX1** [devs-immortal/The-Aether#612]
### What happened?

he animation goes along with the sound, but the portal doesn't work.
I tried to play without other mods, it did not help
(Maybe the portal does not work well with worlds that were created before installing).
https://www.youtube.com/watch?v=U3udsIqGWI4

### Mod Version

1.6.5 - 1.18

### Fabric API Version

last

### Additional Information

https://www.youtube.com/watch?v=U3udsIqGWI4

**Comment by Jack-Papel** [comment]
The video has been removed, and you need to provide log output

**Comment by Jack-Papel** [comment]
Based on the title and caption, this has likely been resolved by the latest release. Let us know.

**Comment by Jack-Papel** [comment]
Likely a duplicate of #638

**Comment by Jack-Papel** [comment]
#638 has been resolved, so this is likely resolved too.
