### ISSUE TITLE
Bug: structures from Mo' Structures spawn on the "floor" (y=-63)

### ISSUE THREAD

**Issue by mbrozzo** [devs-immortal/The-Aether#613]
### What happened?

First of all, I think this bug may be on their part, but I am not sure. I have already created an issue on their github repo (see https://github.com/finallion/The_Graveyard_-FABRIC-/issues/29), which reads as follows:

Structures from The Graveyard spawn on the "foloor" of the Aether dimension from "Paradise Lost - the Aether Reborn" (y=-63). I am not sure if this is a problem on your part or on theirs, but this seems very similar to this issue from Mo' Structures, which happened in the Aether too:
https://github.com/frqnny/mostructures/issues/62

The differences are that:
- volcanic vents from Mo' Structures also spawn in the End and in Eden Ring (from the "Eden Ring" mod),
- volcanic vents from Mo' Structures spawn at y=0.
I suppose that The Graveyard structures would spawn also in the End and in Eden Ring, but those dimension do not allow building under y=0.

Using the configuration to disable the structures in all the biomes used in the Aether works:
      "blacklistedBiomes": [
        "aether_highlands",
        "aether_highlands_forest",
        "aether_highlands_thicket",
        "aether_wisteria_woods",
        "autumnal_tundra",
        "continental_plateau",
        "highlands_shield"
      ]
(these biomes were added to the blacklist of all structures), but there may be name overlaps in biome names I think (for example an hypothetic modname:plains would overlap with minecraft:plains).

![image](https://user-images.githubusercontent.com/22538059/155436852-bd855f87-656c-44be-b113-5ef9522df5c0.png)

![image](https://user-images.githubusercontent.com/22538059/155437613-72eba4a3-fd75-4ef0-9875-45ccc6a1fc81.png)

### Mod Version

1.6.5 - 1.18

### Fabric API Version

0.64.4

### Other mods

- geckolib 3.0.32
- paradise lost 1.6.5.3
- the graveyard 1.5 (without biomes)

**Comment by Jack-Papel** [comment]
Thanks for reporting this. This is indeed an issue on their end. The note about configuration is also interesting. They really should use identifiers instead of just paths. But I'll let them know that. Thanks for reporting.

**Comment by mbrozzo** [comment]
Update: this also seems to happen with awesomedungeon:abandoned_oak_place structure from Awesome Dungeon, but not all of the structures from that mod

**Comment by mbrozzo** [comment]
Ooops, this actually happens with all the structures from said mod, it does not happen with structures from Awesome Dungeons Ocean Edition (presumably because there are no oceans)

**Comment by Jack-Papel** [comment]
Fixed for graveyard mod

**Comment by Jack-Papel** [comment]
Fixed for Awesome Dungeon mod. Have yet to hear back from mo' structures

**Comment by mbrozzo** [comment]
Thank you for the updates!

**Comment by Jack-Papel** [comment]
Closing as it is Mo' Structures' issue to solve
