### ISSUE TITLE
Crash: Crash on startup

### ISSUE THREAD

**Issue by KMFrench1** [devs-immortal/The-Aether#614]
### What were you doing when the crash occured? How can we replicate it?

1. First, ... Start minecraft
2. Next, ... Nothing it charshes

https://paste.ee/p/bojVt

### Did it crash the client or server?

Client

### Mod Version

1.6.5 - 1.18

### Fabric API Version

0.13.3

### Crash Report

```shell
https://paste.ee/p/bojVt
```

### Other mods

https://mega.nz/file/v6hRBQaZ#YHGKeQZrpdsb1LK_3vevHHVMPWObNo4MfX2uGGdJyw4

### Additional Information

Using Multi MC

**Comment by Jack-Papel** [comment]
@gudenau looks like recipe confidence again

**Comment by KMFrench1** [comment]
What that? can do something to fix it somehow?

**Comment by Jack-Papel** [comment]
I was just letting a developer know what they need to fix

**Comment by gudenau** [comment]
They are literally doing what my mod does.

**Comment by gudenau** [comment]
Wait, not exactly the same but the same general idea.

**Comment by gudenau** [comment]
https://github.com/xanthian/variantbarrels/issues/7

**Comment by KMFrench1** [comment]
@gudenau isn't you recipe confidence embedded in the mod. The download page says it is.

**Comment by Jack-Papel** [comment]
It is, yeah. We're getting things figured out

**Comment by xanthian** [comment]
Update Variant Barrels to 1.3, I changed the recipe manager mixin to Inject rather than overwrite.

edit - Variant crafting tables updated also to use new mixin

**Comment by meotisR** [comment]
Same problem

**Comment by KMFrench1** [comment]
This was fixed by the "varient" creator. So closed issue.
