### ISSUE TITLE
Feature: Paradise Lost has no Config File?

### ISSUE THREAD

**Issue by toErIpNid** [devs-immortal/The-Aether#615]
### Problem (Optional)

I was looking for the config and noticed that the mod doesn't have one at all.

### Feature

I need a configurable setting for the damage of the valkyrie lance as it's WAY too overpowered in its current state. It being rare loot doesn't help anything either. 

### Version

1.6.5 - 1.18

**Comment by Jack-Papel** [comment]
The Valkyrie lance is unobtainable at the moment, so we'll modify the attack and such when we implement it fully. Thanks for the report though. A config is a good idea

**Comment by SollyW** [comment]
You could, alternatively, make a small mod and configure it via mixin

**Comment by Jack-Papel** [comment]
Closing. We'll add this when we add things that should be configurable
