### ISSUE TITLE
Bug: TerraBlender incompatibility bug i think?

### ISSUE THREAD

**Issue by Niketats** [devs-immortal/The-Aether#630]
### What happened?

Overworld biomes spawning in Aether
Fabric 1.18.2

To replicate:
1. Install TerraBlender and BYG,
2. Install Paradise lost,
3. Create new world and teleport to Aether, there will be a lot of Overworld biomes

### Mod Version

Beta 1.6.6

### Fabric API Version

0.47.10

### Relevant log output

```Shell
https://pastebin.com/uX50bmfH
```

### Other mods

https://drive.google.com/file/d/1Wl7fcLHPiqQTXfJLHNhEZoJHJVkbU1pJ/view?usp=sharing

**Comment by Jack-Papel** [comment]
Which biomes specifically? Vanilla biomes or BYG biomes?

**Comment by Niketats** [comment]
both

**Comment by Jack-Papel** [comment]
Please forward this to BYG or Terrablender

**Comment by Niketats** [comment]
Yes i do, TerraBlender developer made an update that fix this problem with other dimensions mods like Agape Space Dimensions, but not for Aether. Maybe you can contact him to find a solution?

**Comment by Jack-Papel** [comment]
> Please forward this to BYG or Terrablender

Did you do this? 
https://github.com/Glitchfiend/TerraBlender/issues

**Comment by Jack-Papel** [comment]
Oh it looks like you did

**Comment by Jack-Papel** [comment]
It still doesn't work? You should make another issue or reopen your existing issue there

**Comment by Niketats** [comment]
I wrote him about that in his discord right after update with fix, i think he saw it

**Comment by Niketats** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/59#issuecomment-1086736140

**Comment by Niketats** [comment]
Just use custom dimension type

**Comment by Jack-Papel** [comment]
Resolved in dev builds. Should be good to go for the next release. Thanks for reporting.

**Comment by Niketats** [comment]
Is this patch released? So if yes, i can close this

**Comment by Niketats** [comment]
and i think this issue (https://github.com/devs-immortal/Paradise-Lost/issues/631) was related to same problem https://github.com/Glitchfiend/TerraBlender/issues/59#issuecomment-1086736140 like my issue so you can unpin it
