### ISSUE TITLE
Bug: Other mods' structures and mobs spawning in the Aether

### ISSUE THREAD

**Issue by DaddySpin** [devs-immortal/The-Aether#631]
### What happened?

I seem to be getting Vanilla Mineshafts and the cabins from Subterrestrial spawning in the Aether.

![2022-03-15_12 45 19](https://user-images.githubusercontent.com/34575655/158439449-e093bc66-f062-44a3-a937-d8e480c07842.png)
![2022-03-15_12 41 30](https://user-images.githubusercontent.com/34575655/158439460-6b77bf25-9aae-4136-b698-5a34c71ce19f.png)

### Mod Version

1.6.6

### Fabric API Version

0.48.0

### Other mods

[Subterrestrial 1.0.2](https://www.curseforge.com/minecraft/mc-mods/subterrestrial/files/3670713)

**Comment by Jack-Papel** [comment]
Please forward this to Subterrestrial.
If other mods' structures spawn in The Aether, they need to fix it, because we cannot.

**Comment by Jack-Papel** [comment]
Locked and pinned as reference for others with similar issues

**Comment by Jack-Papel** [comment]
This guidance also applies to other mods' mobs spawning in the aether. Please forward it to the mods in question.
