### ISSUE TITLE
Bug: Shears not working with Aether mod 1.18.2

### ISSUE THREAD

**Issue by AugustusZebulon** [devs-immortal/The-Aether#632]
### What happened?

A bug happened!

Shears work normally without Aether mod but once you load up the aether mod, they just stop shearing sheep. You can snip kelp and break grass and leaves but cannot shear sheep. 

To replicate:
1. Create an instance in MultiMC - Fabric 1.18.2 + Aether + Other mods
2. Start a new world
3. Try to shear sheep

### Mod Version

1.6.6+1.18.2

### Fabric API Version

0.48.0+1.18.2

### Relevant log output

```Shell
https://paste.ee/p/iH1nk
```

### Other mods

https://drive.google.com/file/d/1GTiP5pzIW8Ebl7MC4r5t0NYHG52wMxIv/view?usp=sharing

### Additional Information

Using MultiMC

**Comment by MBatt1** [comment]
Seems to be a MoreTags issue @gudenau, not even a mod conflict, it just doesn't allow shearing with PL alone, I've created a PR in MoreTags to fix it.

**Comment by Jack-Papel** [comment]
This has been fixed in dev builds and will be fixed in the next release. Thanks for reporting

**Comment by MBatt1** [comment]
has it been resolved? I believe it's still broken in b1.7 currently, double check @Jack-Papel ?

**Comment by gudenau** [comment]
3.0.3 should have fixed it.

**Comment by Jack-Papel** [comment]
Don't think the latest version has 3.0.3

**Comment by Jack-Papel** [comment]
This has been fixed in the latest release. Thanks for reporting
