### ISSUE TITLE
Bug: Game extreamly freezes when loading chunks in Aether 

### ISSUE THREAD

**Issue by Niketats** [devs-immortal/The-Aether#633]
### What happened?

So, when I'm entering Aether for the first time game freezes completely, I still can relaunch the game and join the world, but after that game freezes for about 2 secs every time, new chunks are generating.
I think that the problem is in some optimization mods in my mod pack, but I tested Paradise Lost only with all optimization mods and everything was ok, after that, I give up cuz idk what mod can cause these freezes, maybe you can guys? Pleeease

To replicate:
1. Install my modpack,
2. Enter Aether and try to fly around to load chunks

### Mod Version

Beta 1.6.6

### Fabric API Version

0.47.10

### Relevant log output

```Shell
https://pastebin.com/wbjPDYEx
```

### Other mods

https://drive.google.com/file/d/1bERdnWWMAx4yR25FQKImND6X2yhNo2RR/view?usp=sharing

**Comment by Niketats** [comment]
Interesting that there is no freezes with TerraBlender but this https://github.com/devs-immortal/Paradise-Lost/issues/630

**Comment by MBatt1** [comment]
Does it freeze completely or just lag, and does it happen every time?

**Comment by Niketats** [comment]
I think heavy lag

**Comment by Niketats** [comment]
idk why, but this bug was caused by this https://github.com/devs-immortal/Paradise-Lost/issues/630
