### ISSUE TITLE
Feature: Add a config to blacklist other modded mobs from spawning in the Aether

### ISSUE THREAD

**Issue by snotknobbel** [devs-immortal/The-Aether#635]
### Problem (Optional)

Right now it is not possible to prevent certain mobs from spawning, 
the problem is that mobs from bewitchment and better animals plus can spawn in the aether and are preventing the actual aether mobs from spawning.

### Feature

Add a config where you can blacklist mobs, or add a feature where only aether mobs can spawn naturally

### Mod Version

paradise-lost-1.6.5.3+1.18.1

### Additional Information

1.18.1 fabric, with a custom modpack [here](https://www.curseforge.com/minecraft/modpacks/feta-fabric-1-18/relations/dependencies)

**Comment by Azzyypaaras** [comment]
I uh - I am sad to inform you that that is _not_ how mob spawning works. If their mobs are spawning inside the aether then that is a bug on their end.

**Comment by Jack-Papel** [comment]
Please forward this issue to bewitchment and better animals
