### ISSUE TITLE
Bug: modded structures and mobs of overworld spawn in aether

### ISSUE THREAD

**Issue by Chribit** [devs-immortal/The-Aether#649]
### What happened?

Nothing game breaking really. I just noticed structures of the following mods spawn in the aether:
- repurposed structures (e.g. witches hut and underground (overworld) bastion)
- Mo' structures volcanic vents (this is a known bug of the mod, they also spawn in the end)
- the graveyard (e.g. large graveyards, haunted houses, etc.)

Additionally, i've found mobs of the "better animals plus" mod spawning, e.g.:
- butterflies
- boars
As well as hostile mobs of "The Graveyard" mod (same as the one the structures originate from).

Also, not sure if related, but none of the three structures can be located via /locate. They all return "Could not find that structure nearby".

It can be replicated by installing the fabric mods:
- The Graveyard
- Mo' Structures
- Repurposed Structures
And then simply visiting the aether.

Images of proof below:

better animals plus mobs:
![deer](https://user-images.githubusercontent.com/29504473/161217388-4b02875e-6fb4-4983-bc9e-b11fa70aebcd.png)
![songbird](https://user-images.githubusercontent.com/29504473/161217423-cd225090-6d14-4a0e-8224-ffa670f90121.png)
![boar](https://user-images.githubusercontent.com/29504473/161217352-9e819588-815c-4b66-84e0-ff88474c1a7c.png)

graveyard:
![graveyard](https://user-images.githubusercontent.com/29504473/161217406-4a107d89-4dc4-46f5-b498-a5429abc6b06.png)

volcanic vent:
![volcanic_vent](https://user-images.githubusercontent.com/29504473/161217485-3ddd85f5-7bfe-4c59-b791-d21a982e3801.png)

underground bastion:
![underground_bastion](https://user-images.githubusercontent.com/29504473/161217778-33a44cfb-d877-4f8e-899f-245c979eac7d.png)

### Mod Version

Beta 1.6.8

### Fabric API Version

0.46.6

### Other mods

https://drive.google.com/file/d/1r4I4QMsvz4-tNxpQaQd6B2l72oBO_mzq/view?usp=sharing

hope that download via google drive works...
it's ALL the mods in my modpack, most of them are probably not relevant.

**Comment by Jack-Papel** [comment]
Hi, thanks for reporting. I'm going to close this as it's the same issue as the pinned issue. Check it out for a solution

**Comment by Chribit** [comment]
Oh sh*t… sorry about that! I must have overlooked it :)

**Comment by Jack-Papel** [comment]
You're all good. We appreciate the report :)
