### ISSUE TITLE
Bug: Skyroot chests break without dropping itself

### ISSUE THREAD

**Issue by ValynnVisalle** [devs-immortal/The-Aether#653]
### What happened?

I was making skyroot chests for my storage room and miss clicked. When I tried to break it (with my silk touch axe), it just broke without dropping itself. I have not tried this with the other Aether wood chests, but I would be willing to bet they do the same thing. 

To replicate:
1. Place a skyroot chest in creative mode.
2. Combine a silk touch book with an axe.
3. Set gamemode to survival.
4. Try to break the chest.  

The result should be just a destroyed chest with no drop. 

### Mod Version

Beta 1.18.1 - 1.6.8

### Fabric API Version

0.4.2

**Comment by Jack-Papel** [comment]
Looks like we have some missing loot tables. Thanks for reporting.

**Comment by ValynnVisalle** [comment]
You're welcome. Thank you for the quick response. 
Another loot table you may want to look at is the flax plant. Right now, the only thing it drops is the string and no seeds to replant. I really like the cushion that you can make with it, but I have found no way to get the seeds currently.

**Comment by Jack-Papel** [comment]
@MBatt1 Are you on spring break? If not, I'd appreciate it if you could get these in. Otherwise, I could also do it later when I'm back in town on Monday

**Comment by MBatt1** [comment]
I wish I was still on break, but I can knock em out real quick

**Comment by Jack-Papel** [comment]
Thanks

**Comment by MBatt1** [comment]
Resolved! Also noticed the other chests were missing from the "aether_wooden_chests" tag so fixed that as well

**Comment by MBatt1** [comment]
whoops
