### ISSUE TITLE
Crash: Right after starting client

### ISSUE THREAD

**Issue by TheButterbrotMan** [devs-immortal/The-Aether#654]
### What were you doing when the crash occured? How can we replicate it?

1. First, start client.
2. Next, wait.
3. Finally, crash.

### Did it crash the client or server?

Server

### Mod Version

1.6.8+1.18.2

### Fabric API Version

0.50.0+1.18.2

### Crash Report

```Shell
https://bytebin.lucko.me/5g9yc349gF
```

### Other mods

https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment]
https://github.com/Lemonszz/Biome-Makeover/issues/97

**Comment by TheButterbrotMan** [comment]
Resolved by https://github.com/architectury/architectury-api/issues/241#issuecomment-1095009196

**Comment by TheButterbrotMan** [comment]
It havent.

https://bytebin.lucko.me/KzQgUEn2Et

**Comment by netcore10** [comment]
i also get it crashing on launch
[latest.log](https://github.com/devs-immortal/Paradise-Lost/files/8515317/latest.log)

**Comment by MBatt1** [comment]
Appears to be a BClib incompatability, duplicate of #664
