### ISSUE TITLE
Bug: Repurposed Structures Mineshafts in Aether

### ISSUE THREAD

**Issue by itsdinkd** [devs-immortal/The-Aether#666]
### What happened?

Visited Aether and spotted a repurposed structures mineshaft.  running /locate, there are a bunch in the aether

![image](https://user-images.githubusercontent.com/35115304/166115448-2fe7be80-3b0c-404b-9934-2a2520efd66d.png)

### Mod Version

1.6.8

### Fabric API Version

51.1

**Comment by Jack-Papel** [comment]
This has been resolved in dev builds, and will be fixed in the latest update
