### ISSUE TITLE
Paradise Lost Crashes when loaded with Create's fabric port

### ISSUE THREAD

**Issue by EmpressAutumn** [devs-immortal/The-Aether#667]
### What were you doing when the crash occured? How can we replicate it?

1. install Fabric API 0.51.1 (latest)
2. install Create 0.4.1+534 (latest) [from here](https://github.com/Fabricators-of-Create/Create/actions/workflows/build.yml)
3. install Paradise Lost 1.6.8 (latest)
4. launch game with Fabric Loader 0.13.3

### Did it crash the client or server?

Client

### Mod Version

Beta 1.6.8

### Fabric API Version

0.51.1

### Crash Report

```Shell
https://pastebin.com/ut7Vy5dC
```

### Other mods

Mods are as listed in Replication Steps, but can also be downloaded [here](https://www.mediafire.com/file/abp0r5e01ywcp71/mods.zip/file).

**Comment by EmpressAutumn** [comment]
I also left this as an issue on the Create mod's GitHub, as I am unsure whether it is caused by this mod or theirs.

**Comment by Tenuuu** [comment]
Having similar issue on 1.6.9 of Paradise Lost

**Comment by Azzyypaaras** [comment]
Hm, seems to be crashing due to shaders. Perhaps there is a conflict in regards to how we apply them?

@gudenau would be more knowledgeable about this

**Comment by EmpressAutumn** [comment]
According to the Create devs, this is likely caused by the boreal wisteria leaf shader.

**Comment by blacksabin** [comment]
Is this related/the same thing as https://github.com/devs-immortal/Paradise-Lost/issues/665? Which can confirm, I have attempted using both releases of Create with both releases of Paradise Lost for 1.18.2, no combination of them will work.

**Comment by gudenau** [comment]
Considering the only way for that registry to be locked is by getting the render layers, I would say that create is doing something funky.

Our render layers are registered about as early as possible.

Related code from Satin:
```Java
public final class BlockRenderLayerRegistry {
    public static final BlockRenderLayerRegistry INSTANCE = new BlockRenderLayerRegistry();
    private final Set<RenderLayer> renderLayers = new ObjectArraySet<>();   // ArraySet for faster iteration
    private volatile boolean registryLocked = false;
    
    private BlockRenderLayerRegistry(){}
    
    public void registerRenderLayer(RenderLayer layer) {
        if(registryLocked){
            throw new IllegalStateException(String.format(
                "RenderLayer %s was added too late.",
                    layer
            ));
        }
        
        renderLayers.add(layer);
    }
    
    public Set<RenderLayer> getLayers() {
        registryLocked = true;
        return renderLayers;
    }
}
```

**Comment by Jack-Papel** [comment]
Needs confirmation if this still occurs in 0.2.0

**Comment by EmpressAutumn** [comment]
I'll test this once Create Fabric is updated to 1.19

**Comment by TropheusJ** [comment]
will be fixed in next Create release

**Comment by EmpressAutumn** [comment]
Just tested it today, I'm glad to say the incompatibility is fixed.
