### ISSUE TITLE
Bug: Gravitite Levitator duplicates blocks

### ISSUE THREAD

**Issue by HacoKavanah** [devs-immortal/The-Aether#670]
### What happened?

A bug happened! My friend thought we should use this to duplicate ancient debris, I thought to put it in quarantine.

To replicate:
1. First, place blocks on levitator, leave redstone torch on ground.
2. Next, the levitator rises up. The blocks on top of it either duplicate here, or when coming back down and going back up again.

### Mod Version

 paradise-lost-1.6.9+1.18.2.jar

### Fabric API Version

 fabric-api-0.51.1+1.18.2.jar

**Comment by MBatt1** [comment]
Unable to reproduce on 2.0.0
