### ISSUE TITLE
Bug: PL breaks overworld generation?

### ISSUE THREAD

**Issue by TheAyes** [devs-immortal/The-Aether#675]
### What happened?

I'm tryinig to set up a server using paradise lost however everytime I enable the mod and generate a world the outsides of the spawn area are largely offset in terms of height.
I'm also using a few other mods for world generation, but I'm assuming it's caused by this mod since removing it resolves the issue.

To replicate:
1. Enable Paradise lost
2. Generate a world with the fabric server jar
2b. most likely it will crash the server. restart.
4. fly outside the spawn area
5. observe

![image](https://user-images.githubusercontent.com/68541335/168992702-49a21a5d-36b3-4fc5-a0a5-108c3e97600c.png)

### Mod Version

1.6.9

### Fabric API Version

0.51.1

### Other mods

https://drive.google.com/file/d/1HS6U632Sr14sGtKuvCBwEyZSpXCldMO5/view?usp=sharing

**Comment by TheAyes** [comment]
Update: This issue seems to be related to the forced crash upon first world start. While suppressing this crash works I'm not certain if that is the way it's supposed to be.

**Comment by TheAyes** [comment]
Update 2: Restarting the server THEN causes the same issue again.
![image](https://user-images.githubusercontent.com/68541335/169082714-ea4695c0-83e7-4bb9-9ddf-835a22fb9093.png)

**Comment by TheAyes** [comment]
I've discovered a workaround which is doing the following:
1. Let the server generate the world for the very first time (The MC Bug will prevent the The Aether from being added)
2. Let the server crash
3. Restart the server and let it add the aether
4. stop the server and delete the "region" directory in your world folder
5. restart the server
6. profit

**Comment by gudenau** [comment]
I am working on fixing the issue with the world not existing, hopefully that should also fix this.
