### ISSUE TITLE
Similar color in clouds

### ISSUE THREAD

**Issue by Slainlight** [devs-immortal/The-Aether#68]
the blue aercloud and cold aercloud are very similar in color
The new style is great, but make the cold aercloud more white and the blue aercloud bluer

These are difficult to differentiate.
![2020-12-23_09 36 50](https://user-images.githubusercontent.com/18296791/103008020-6ca5fa00-4502-11eb-8135-d703a8c4fd73.png)
For reference, the left is cold aercloud and the right is blue aercloud.

These are distinct and easy to see.
![2020-12-23_09 33 56](https://user-images.githubusercontent.com/18296791/103007800-0c16bd00-4502-11eb-8f1a-71f3ee35c487.png)

**Comment by MBatt1** [comment]
I have adjusted colors and textures, someone should update this with opinions on current textures
