### ISSUE TITLE
Crops don't behave like they do in vanilla

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#680]
Breaking a flax crop in creative drops flax thread and flaxseed, while in vanilla, breaking wheat drops nothing.

Planting flaxseed does not grant the "A seedy place" advancement

**Comment by MBatt1** [comment]
I propose we make a new advancement for planting a paradise crop, as we add more

**Comment by MBatt1** [comment]
fixed, but requires latest incubus core changes
