### ISSUE TITLE
Moa Armor

### ISSUE THREAD

**Issue by Shaunster1** [devs-immortal/The-Aether#685]
### Feature

It would be cool if you can Moa get armor like horse armor, but you can use gravitite to buff there flight, and when the bosses get added, what if the **valkyrie** **queen** drop an item that can be used to upgrade the gravitite Moe Armor, a valkyrie feather, applying it in a smithing table would give it a dash similar to how a rocket boosts an elytra, but has a short cool down between every dash.

### Mod Version

Beta 1.6.9

**Comment by MBatt1** [comment]
Not pursuing. Moas are already very strong
