### ISSUE TITLE
Crash: 

### ISSUE THREAD

**Issue by Satanicsylveon** [devs-immortal/The-Aether#688]
### What were you doing when the crash occured? How can we replicate it?

1. First, i had crafted the farming staff from in the Gobber[Fabric] mod
2. Next, then i right clicked to grow the crops while holding the staff
4. Finally, which then shortly after make the game crash

### Did it crash the client or server?

Both

### Mod Version

1.18.1

### Fabric API Version

0.13.3

### Crash Report

```Shell
java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to -4 on Block{the_aether:flax}, it is not an allowed value
```

### Other mods

[Gobber2-Fabric-1.18.1-2.5.63.3.zip](https://github.com/devs-immortal/Paradise-Lost/files/8865950/Gobber2-Fabric-1.18.1-2.5.63.3.zip)

### Additional Information

the file for all mods was too big but i think it is really only the one mod that caused the issue.
though this might even be a bug causing crashes

**Comment by Jack-Papel** [comment]
When you receive the crash report, there should be a button for more information. Please send that, so we can diagnose the issue better

**Comment by Satanicsylveon** [comment]
[crash-reports_crash-2022-06-08_20.46.30-server.txt](https://github.com/devs-immortal/Paradise-Lost/files/8866374/crash-reports_crash-2022-06-08_20.46.30-server.txt)

@Jack-Papel  not sure if you saw this yet but here is what i was able to get for the crash report
