### ISSUE TITLE
1.19 version

### ISSUE THREAD

**Issue by FulcrumGame** [devs-immortal/The-Aether#695]
Forgive me dear developers, I understand that the free development of such mods and porting to new versions is a job in which no one can rush you!
It's just that since childhood I have been in love with this "dangerous paradise" mod and just wanted to know - will the 1.19 version appear soon?
Thanks a lot for the development ♥

**Comment by Jack-Papel** [comment]
Thanks for the kind message. The 1.19 version is under development. We have run into a few setbacks, but the port is well under way

**Comment by Hedwig7s** [comment]
> Thanks for the kind message. The 1.19 version is under development. We have run into a few setbacks, but the port is well under way

It's been a few months now
How's the port going? Definitely seeing alot of X in the actions tab
