### ISSUE TITLE
(1.18) Game crashes when using QuestCraft VR

### ISSUE THREAD

**Issue by Greenknight9000** [devs-immortal/The-Aether#704]
[latestlog.txt](https://github.com/devs-immortal/Paradise-Lost/files/9221112/latestlog.txt)
Upon trying to load Paradise Lost via QuestCrash on Quest 2, the game doesn't load and appears that Paradise Lost is the cause of the crash.

**Comment by TecEash1** [comment]
> [latestlog.txt](https://github.com/devs-immortal/Paradise-Lost/files/9221112/latestlog.txt) Upon trying to load Paradise Lost via QuestCrash on Quest 2, the game doesn't load and appears that Paradise Lost is the cause of the crash.

Btw ur 'latest log' is blank
