### ISSUE TITLE
Crash: Incompatibility with Deeper and Darker/Alloy Forgery? on 1.19/1.19.2 , Also crashes without No Chat Reports

### ISSUE THREAD

**Issue by TalEdd** [devs-immortal/The-Aether#708]
### What were you doing when the crash occured? How can we replicate it?

- It crashes on launch with error saying it's due to [Alloy Forgery](https://modrinth.com/mod/alloy-forgery) or [Deeper Darker](https://modrinth.com/mod/deeperdarker).
  - Tried it on 1.19 and 1.19.2(I don't play this version).

- Crashes on launch without No Chat Reports on 1.19.2, required dependency perhaps?

- Crashes on 1.19 with error 'Incubus Core'. Library not supported on 1.19?

### Did it crash the client or server?

Both

### Mod Version

Beta 0.2.0

### Fabric API Version

0.58.0/0.60.0

### Crash Report

1.19 with Modpack: 4 Crash Reports attached
https://gist.github.com/TalEdd/bebf8db1a532b609639831a7338e8950

1.19 Clean (Just Fabric API, No Chat Reports, Paradise Lost and Trinkets): 
[crash-2022-09-15_14.14.01-client.txt](https://github.com/devs-immortal/Paradise-Lost/files/9572397/crash-2022-09-15_14.14.01-client.txt)
[crash-2022-09-15_14.31.19-client.txt](https://github.com/devs-immortal/Paradise-Lost/files/9572510/crash-2022-09-15_14.31.19-client.txt)

1.19.2 with Modpack: 2 Crash Report
https://gist.github.com/TalEdd/3d0a1f27c9e2be3048ff9a25e3e0b594

1.19.2 Clean (Works without Trinkets somehow? 🤷‍♂️) :
Launches perfectly fine as long as No Chat Reports is loaded together.

### Other mods

Too many mods as its a custom modpack, 466 mods for 1.19 and 266 mods for 1.19.2.

I can still try to send them, if its really necessary.

### Additional Information

Using PolyMC Launcher.

**Comment by MBatt1** [comment]
noChatReports has been removed, and the incompatibility with alloy forgery has been resolved in the latest version.
