### ISSUE TITLE
Bug: No trees generating in world except in minecraft:grove, in 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [devs-immortal/The-Aether#709]
### What happened?

A bug happened!

To replicate:
1. Create a new world
2. Look for forest biomes, no trees should be there
3. Look for minecraft:grove, some trees should be there

![2022-09-15_14 44 18](https://user-images.githubusercontent.com/63492921/190334790-76b45ba2-69d2-436c-9f99-c02c87fcec96.png)
![2022-09-15_14 44 26](https://user-images.githubusercontent.com/63492921/190334820-316766a1-af7a-45b3-a00b-a179fcc2d8c5.png)
![2022-09-15_14 47 06](https://user-images.githubusercontent.com/63492921/190334841-50d3f81e-aeba-47c5-9578-2ae587deff71.png)

### Mod Version

Beta 0.2.0

### Fabric API Version

0.61.0

### Relevant log output

```Shell
No logs, just screenshots
```

### Other mods

No Chat Reports, Fabric API, Trinkets

### Additional Information

Using PolyMC

**Comment by Defetyre** [comment]
I have same issue, you are also unable to place any vegetation and if any is generated, it will disappear on block update

**Comment by Jack-Papel** [comment]
Should be fixed now. Do you still get this issue?
