### ISSUE TITLE
Getting aerbunny meat is annoying

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#712]
Sometimes it can take up to like 20 aerbunnies before one drops meat. This makes it hard to get meat, which is required for moa breeding. Aerbunnies themselves are not that common, so finding 20 isn't trivial.

Reported by Oz

**Comment by MBatt1** [comment]
in 1.19.3 rabbits drop meat 100% of the time, because it makes more sense. Aerbunnies will do the same.
