### ISSUE TITLE
Bug: Quicksoil Ridable entity momentum 

### ISSUE THREAD

**Issue by SylisMC** [devs-immortal/The-Aether#721]
### What happened?

- Quicksoil Momentum is saved in boatsafter dismounting them. (Boat on qiucksoil, hold D 5 sec, get out & back in)
- Striders and pigs lose all momentum when removing "On a Stick" item from hand
- Entities lose all momentum when a player dismounts
- Minecarts and unaffected by quicksoil (could be a cool super booster for rails)

### Mod Version

paradise-lost-0.2.0-beta+1.19.jar

### Fabric API Version

fabric-api-0.66.0+1.19.2.jar

**Comment by SollyW** [comment]
#0 is a vanilla bug, The same thing happens on ice. I believe the same is true for #1 and #2. Minecarts don't use the same movement mechanics as other entities; they aren't affected by ice, soul sand nor quicksoil
