### ISSUE TITLE
Only biome that is loading is the highlands thicket.

### ISSUE THREAD

**Issue by Canters1** [devs-immortal/The-Aether#722]
### What happened?

Saw some videos on the mod thought it was cool, added it to a server w/ a friend, made a portal walked in.
We spawned in the highlands thicket and didn't think anything of it. Walked around for like 30 min and didnt see anything except for the bigass trees that are in the highlands thicket. Walked around for 30 more mins, same story. Finally, I gave up and /located a biome of anything except for the highlands thicket. All returned couldn't find a biome of that type within reasonable distance. Am I just dumb and this is how it is supposed to be? Or did I do something wrong with the installation.

### Mod Version

Beta 2.0

### Fabric API Version

0.64.0

### Other mods

[all mods used.zip](https://github.com/devs-immortal/Paradise-Lost/files/9976229/all.mods.used.zip)
Also used twilight forest and a couple of libraries, had to delete b/c went over max size allowed.

### Additional Information

Did this on Aternos

**Comment by Jack-Papel** [comment]
This is a known bug that happens on some worlds. We're working to fix it. Thanks for reporting.
