### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by leytilera** [devs-immortal/The-Aether#73]
When I try to launch the client, it crashes and I get this error:
"net.fabricmc.fabric.impl.resource.loader.ResourceManagerHelperImpl.get(Lnet/minecraft/class_3264;)Lnet/fabricmc/fabric/api/resource/ResourceManagerHelper;"

**Comment by PaulZappia** [comment]
I've got this exact same problem. Even the older versions seem to crash. Hopefully this gets fixed soon.

**Comment by CDAGaming** [comment]
@PaulZappia Can you attach your latest.log here with the crash?

It can be found in your .minecraft/logs folder once the game crashes

**Comment by PaulZappia** [comment]
> @PaulZappia Can you attach your latest.log here with the crash?
> 
> It can be found in your .minecraft/logs folder once the game crashes

Here it is: https://paste.ee/p/HIXJj

**Comment by Kichura** [comment]
GeckoLib must be enabled for the mod to work, Otherwise it won't start.

**Comment by PaulZappia** [comment]
> GeckoLib must be enabled for the mod to work, Otherwise it won't start.

Ah, didn't know that. I didn't remember seeing anything on the modrinth page about it.
