### ISSUE TITLE
Suggestion: Aether I-inspired terrain & scaled-down biomes

### ISSUE THREAD

**Issue by TheGag96** [devs-immortal/The-Aether#734]
### Problem (Optional)

Just entered the Paradise for the first time last night after being very excited to try out this mod. I spawned in the Autumnal Tundra and noticed that the terrain around me was incredibly flat and spacious with a few large holes in it. The next biome was hundreds of blocks over, which again was very similar in size and flatness. However, I generated a test world and found myself spawning in a Highland Thicket, which seemed pretty endless in area but at least fairly varying in height. 

This reminded me in a negative way of modern versions of Aether II a  bit: I believe GG made a huge mistake in reworking the terrain of the Aether to be large, flat islands instead of the sky dimension shape that Aether I had that gave it its identity. A huge draw of the Aether was its strange and unique terrain that was traversed far differently than the overworld. You had to stay very aware that you were on a floating structure and could easily fall if you weren't careful. Back then, GG gave this up for a world setup that's much more boring - yes, the lore is still that you're walking around on islands floating in the air, but you hardly have to treat it that way unless you're close to the edges of the islands.

My experience with PL so far has suggested these problems but probably even worse. Walking through it felt much like walking around the overworld with different biomes. I could walk to certain places and forget that I was on a floating island at all. My few minutes flying around above the Highland Thicket in Creative mode was spent looking at basically a solid color. That seems like an issue worth fixing. 

All of this really shocked me too, because the [screenshots on the README](https://user-images.githubusercontent.com/53229958/120235855-92a59800-c220-11eb-994f-889c843beb5b.png) suggested the terrain was very much like Aether I. Did something change recently?

Sorry if this all comes off a tad harsh - I hope you'll at the very least take these two cents to heart. I'd just like to see this mod be the best it can be! Thanks.

### Feature

The worldgen should be reworked to be closer to the original Aether I. Lots of height variance, overhangs, small-to-medium-sized islands, holes in the ground - you should be able to see the bottom of the sky from most vantage points.

### Mod Version

Beta 0.2.0

**Comment by Jack-Papel** [comment]
Hi, we appreciate the report! 1.19 kind of borked our terrain generation - and we agree with what you say. The team is looking at ways to fix this, and to return things to how they were previously.

**Comment by TheGag96** [comment]
No kidding, it's a bug?? Well that explains it, lol. Thanks for looking into it!

**Comment by TheGag96** [comment]
Thanks for taking a crack at this so quickly!! Just compiled and tested on my server. It's definitely a lot better! Although, in the Tradewinds biome, I didn't see any quicksoil overhangs. Are they supposed to be there?

**Comment by MBatt1** [comment]
they are haha, still doing some last fixes with a few features and some other bugs

**Comment by TheGag96** [comment]
> they are haha, still doing some last fixes with a few features and some other bugs

Did you ever fix this before release? It didn't seem like it from the commits but I could be blind lol.

**Comment by MBatt1** [comment]
> > they are haha, still doing some last fixes with a few features and some other bugs
> 
> Did you ever fix this before release? It didn't seem like it from the commits but I could be blind lol.

We are currently reevaluating some features as we move further away from content pulled from the Aether, at this point it looks like quicksoil may not be returning :( sorry!

**Comment by TheGag96** [comment]
That's disheartening... The quicksoil ridges were a distinct part of the Aether's visual style. What exactly does Paradise Lost intend to be as a mod?

**Comment by MBatt1** [comment]
Just another skylands style mod. We are striving to define our own distinctive style and story, which one day might be able to be enjoyed along side the official Aether mod, as the original has picked up speed and become updated to more recent versions

**Comment by TheGag96** [comment]
I've been thinking about this response, and I'd like to give my two cents (for what it's worth).

It seems to me this direction is a mistake for the following reasons:

* I have seen some extra movement on the official Aether mod lately. However, I'm waiting to see a real CurseForge release before I consider the mod "back" in development. I've been seeing GitHub branches named "1.16", "1.18", etc. for a couple years now without any official release.  (Will this momentum even continue past 1.19? Is Forge going to make hell porting it to newer versions if they fall behind by the next Minecraft update?)
* Even if they do get things updated to 1.19+, it will not be compatible with Fabric, meaning PL as a "Fabric version of the Aether" already fills a niche that GildedGames probably never will. 
* What do you think GG and crew realistically are going to do to Aether I? Are they just going to maintain the old b1.7.3 content, maybe adding a few convenience blocks and just leave it at that? That's my guess - I would think most of their creative energy is going to be spent on Aether II, which people like me have no interest in playing due to its heavy departure from I. PL could decide to expand upon/tweak the Aether's lore and have full creative liberty to make new kinds of locales/dungeons/bosses/etc. in the spirit of the original Aether in ways GG probably won't ever do.

I'm just some guy, so obviously take or leave what I've said, haha. But I hope your team is thinking about these kinds of things. Going your own direction may prove cool after all - though I still worry that there could be missed potential.

**Comment by MBatt1** [comment]
Your 2 cents are absolutely worth, PL is currently in the process of departing from deriviative Aether content, ie no zanite, no skyroot, no holystone, but we are creating similar blocks and materials, but giving us a lot of freedom to make new, fresh content. I think this might worry some people, but we're aiming to stay in the "spirit" of how the original Aether felt, or somewhat how the current nether feels, polish wise.

We will be going a different direction, but aim to share the same feel that a skylands dimensions provides. Freeing ourselves from the content retained directly from the Aether opens up unlimited possibilities, making it far easier to add new interesting features and items.

I'm not sure there ever will be an Aether 1 for Fabric, but hopefully PL still will feel like a mod that captures the feel of what Aether 1 is.

**Comment by StockiesLad** [comment]
Actually, there good tools like porting lib & a community that could aid an aether I fabric port. I personally think that aether I will eventually be on fabric. Which means in the case of that, PL would need to be different enough from aether I to be mutually playable with Aether I.

**Comment by TheGag96** [comment]
> mutually playable with Aether I.

I think this is part of what I'm talking about. I'm having a hard time imagining that people would want *two* "opposite-of-the-Nether" dimensions with vaguely similar concepts/lore in the same modpack. It seems wise to design PL with the expectation that people would choose to play it *instead of* the Aether, not alongside.

**Comment by MBatt1** [comment]
I'm sure some people would like to play them side by side, given the different directions that PL is going, even just mechanically, is quite different from where Aether II will end up eventually. This is of course assuming Aether is officially ported, which will likely be a while while GG polishes up the Aether for Forge.

**Comment by StockiesLad** [comment]
> Contributor

I would be one of them. I dont want to lose my cool clouds
