### ISSUE TITLE
Aether Portal sounds are much louder than nether portal sounds

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/The-Aether#737]
Reported by SpaceWalker on discord
https://discord.com/channels/770691727568404521/770691728528769036/1047011372237586474

> it's much louder than the nether portal sound

> ... it needs to be quite a lot quieter lol

**Comment by MBatt1** [comment]
I reduced the sound volume to be as close to the nether portal ambience in 2.1.0, they should be noticeably almost the same
