### ISSUE TITLE
Bug: Paradise lost is breaking some leaf textures from other mods due to christmas ornaments.

### ISSUE THREAD

**Issue by StockiesLad** [devs-immortal/The-Aether#748]
### What happened?

A bug happened!

To replicate:
1. Install paradise lost & BYG (Or any mod that adds leaves)
2. Some leaves will not have textures.

### Mod Version

Beta 1.6.9 1.18.2

### Fabric API Version

0.67.0

### Relevant log output

```Shell
https://gist.github.com/FluffyBumblebees/3862e4b0fff36bc84c82630e7c72ff42
```

### Other mods

BYG

**Comment by aeaver** [comment]
It seem that i was able to replicate this bug by installing sodium with byg and lost paradise, when i remove sodium both lost paradise and byg leaf's start to have texture

For me:

1.  BYG + Paradies  Lost (no sodium) = load
2.  BYG + Sodium = load
3.  Paradies  Lost + Sodium = does not load
4.  BYG + Paradies  Lost + Sodium = does not load

### Mod Version
Release 1.4.7 1.18.2 

### Fabric API Version
0.67.0

**Comment by StockiesLad** [comment]
Ah its a sodium incompat. Kinda annoying that there isnt a config to atleast turn this off until there's a fix.

**Comment by aeaver** [comment]
I am currently using these 3 mods with my friend in a modded server, from his point of view the BYG and paradise lost leaf does load, but chest from paradise lost does not load

**Comment by MBatt1** [comment]
We actually don't have christmas textures for the chests that's why they're untextured. I believe the leaf problems are fixed in the 1.19.x versions however, but I will make a not of both.

**Comment by Frontear** [comment]
1.19.2 Modpack MedievalMC users have reported this exact issue as well. Most notably, leaf textures from BYG are missing and are replaced with the purple/black texture.

**Comment by StockiesLad** [comment]
This is fixed in my PR.

**Comment by Samurai-Lemon** [comment]
im still experiencing this currently on 1.21.1
