### ISSUE TITLE
Missing texture assets via creative mode.

### ISSUE THREAD

**Issue by Kichura** [devs-immortal/The-Aether#75]
When having creative mode enabled, Viewing the second page of creative items reveals missing assets (*Ahem* CS:S missing reference not intended) of misc. items and others.

+ I am unaware if there is a similar issue related to this but i just can't really confirm myself.
![mc](https://user-images.githubusercontent.com/68134602/103652666-b6133200-4f63-11eb-8ab2-e1ad5333c4b0.png)

**Comment by MBatt1** [comment]
Several textures are still needing to be completed.
