### ISSUE TITLE
Crash: cannot open with other mods

### ISSUE THREAD

**Issue by asdfghjkl403622** [devs-immortal/The-Aether#754]
### What were you doing when the crash occured? How can we replicate it?

1. Launch the game with various other mods

### Did it crash the client or server?

Client

### Mod Version

Beta 2.0.2

### Crash Report

```Shell
https://mclo.gs/KoB4gpF
```

### Other mods

$ tree
.
├── AdaptiveTooltips-1.0.1-fabric-1.19.2.jar
├── ad_astra-fabric-1.19.2-1.12.2.jar
├── AdditionalAdditions-5.1.0.jar
├── Adorn-3.8.1+1.19.2-fabric.jar
├── advancednetherite-fabric-1.6.6-1.19.2.jar
├── AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
├── anti-xray-1.3.0-Fabric-1.19.2.jar
├── appleskin-fabric-mc1.19-2.4.1.jar
├── architectury-6.4.62-fabric.jar
├── artifacts-7.1.1+fabric.jar
├── AutoModpack-1.19.x.jar
├── badpackets-fabric-0.2.1.jar
├── balm-fabric-4.5.2+0.jar
├── bclib-2.1.5.jar
├── better-enchanted-books-1.19-1.4.1.jar
├── better-end-2.1.2.jar
├── better-end-sky-0.1.1.jar
├── BetterF3-4.0.0-Fabric-1.19.2.jar
├── better-nether-7.1.2.jar
├── BetterPingDisplay-Fabric-1.19.2-1.1.1.jar
├── BOMD-1.4.6-1.19.2.jar
├── Bookshelf-Fabric-1.19.2-16.2.17.jar
├── boosted-brightness-2.1.2+1.19.jar
├── BotanyPots-Fabric-1.19.2-9.0.24.jar
├── BotanyTrees-Fabric-1.19.2-5.0.4.jar
├── botarium-fabric-1.19.2-1.8.2.jar
├── BuildingWands_mc1.19.2-2.6.5_beta-fabric.jar
├── c2me-fabric-mc1.19.2-0.2.0+alpha.9.5.jar
├── cammies-minecart-tweaks-1.6.jar
├── cardinal-components-api-5.0.2.jar
├── cc-restitched-1.101.2.jar
├── charm-fabric-1.19.2-4.4.4.jar
├── charmonium-fabric-1.19.2-4.2.1.jar
├── chat_heads-0.9.0-fabric-1.19.2.jar
├── ClearDespawn-fabric-1.19.2-1.1.10.jar
├── clientcommands-2.7.5.jar
├── cloth-config-8.2.88-fabric.jar
├── combatroll-fabric-1.1.2+1.19.jar
├── comforts-fabric-6.0.3+1.19.2.jar
├── continuity-2.0.1+1.19.jar
├── cookingforblockheads-fabric-1.19.2-13.3.0.jar
├── Cosmetica 1.2.2 1.19.1.jar
├── craftable-potion-combinations-1.0.0+1.19.jar
├── CraftTweaker-fabric-1.19.2-10.0.29.jar
├── createaddition+1.19.2-1.19.2-20221218a.jar
├── create_crystal_clear-1.0+1.19.2.jar
├── create-fabric-0.5.0g-796+1.19.2.jar
├── CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
├── crops_love_rain-1.3.0.jar
├── culinaire-2.5.0.jar
├── dark-loading-screen-1.6.12.jar
├── DarkPaintings-Fabric-1.19.2-13.1.5.jar
├── dataattributes-1.4.0.jar
├── dawn-3.5.0.jar
├── day-dream-1.0.5.jar
├── deathlog-0.2.11+1.19.jar
├── Decorative Blocks-fabric-1.19.2-3.0.0.jar
├── disenchanter-0.1.7+1.19.jar
├── dynamiccrosshair-5.0+1.19.2-fabric.jar
├── dynamiccrosshair-compat-3.1+1.19.2.jar
├── easiercrafting-1.19.1-fabric0.58.5-1.7.jar
├── easiervillagertrading-1.19.1-fabric0.58.5-1.5.4.jar
├── eden-ring-0.6.4.jar
├── EditSign-1.19.2-2.6.0.jar
├── enchantment-lore-1.3.0-b1+MC1.19.1-1.19.2.jar
├── essential_commands-0.30.0-mc1.19.2.jar
├── expanded-armor-enchanting-1.0.3.jar
├── ExplorersCompass-1.19.2-2.2.0-fabric.jar
├── ExtendedDrawers-1.3.6+mc.1.19.2.jar
├── extraalchemy-fabric-1.19.2-1.9.0.jar
├── fabric-api-0.73.0+1.19.2.jar
├── fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar
├── FallingTree-1.19.2-3.10.0.jar
├── farmers-delight-fabric-1.19.X-1.3.9.jar
├── fastback-0.7.4+1.19.2.jar
├── FauxCustomEntityData-fabric-1.19.2-2.0.2.jar
├── ferritecore-5.0.3-fabric.jar
├── foodeffecttooltips-1.0.1-1.19.2.jar
├── ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric.jar
├── frame-0.26.1+1.19-fabric.jar
├── geckolib-fabric-1.19-3.1.38.jar
├── haema-1.10.4+1.19.jar
├── haema-1.10.4+1.19.jar.disabled
├── hexcasting-fabric-1.19.2-0.10.3.jar
├── iammusicplayer-fabric-mc1.19.2-3.19.6.jar
├── IKnowWhatImDoing-4.1.1-fabric.jar
├── immersive_aircraft-0.2.0+1.19.2.jar
├── immersive_paintings-0.4.4+1.19.2-fabric.jar
├── immersive_weathering-1.19.2-1.2.3-fabric.jar
├── IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
├── inventorytabs-0.9.beta-1.19.x.jar
├── jamlib-0.6.0+1.19.jar
├── journeymap-1.19.2-5.9.2-fabric.jar
├── krypton-0.2.1.jar
├── lambdabettergrass-1.3.0+1.19.jar
├── lazydfu-0.1.3.jar
├── libIPN-fabric-1.19-2.0.1.jar
├── light-overlay-7.0.0.jar
├── litematica-fabric-1.19.2-0.12.6.jar
├── lithium-fabric-mc1.19.2-0.10.4.jar
├── lootr-1.19-0.4.25.64.jar
├── lovely_snails-1.1.0+1.19.jar
├── MagnumTorch-v4.2.1-1.19.2-Fabric.jar
├── malilib-fabric-1.19.2-0.13.0.jar
├── MCDiscordChat-1.19.2-2.1.2.jar
├── megane-8.3.0.jar
├── midnightlib-fabric-1.0.0.jar
├── moborigins-1.9.0.jar
├── modmenu-4.1.2.jar
├── monsters-in-the-closet-1.0.3+1.19.jar
├── moonlight-1.19.2-2.1.9-fabric.jar
├── morechatsuggestions-1.0.2.jar
├── more-discs-1.19.2-27.jar
├── MouseTweaks-fabric-mc1.19-2.22.jar
├── mousewheelie-1.10.7+mc1.19.2.jar
├── MTR-fabric-1.19.2-3.2.0.jar
├── NaturesCompass-1.19.2-2.1.0-fabric.jar
├── nicer-skies-1.2.0+1.19.2.jar
├── NoChatReports-FABRIC-1.19.2-v1.13.12.jar
├── no-telemetry-1.5.0.jar
├── notenoughanimations-fabric-1.6.2-mc1.19.2.jar
├── Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar
├── openblockselevator-0.0.2-1.19.X.jar
├── Origins-1.19.2-1.7.1.jar
├── otyacraftengine-fabric-mc1.19.2-3.2.0.jar
├── owo-lib-0.9.3+1.19.jar
├── oxidized-1.7.2.jar
├── Paintings-fabric-1.19.2-10.2.4.0.jar
├── paladin-furniture-mod-1.1.1-fabric-mc1.19.jar
├── paradise-lost-2.0.2-beta+1.19.2.jar
├── Patchouli-1.19.2-77-FABRIC.jar
├── paucal-fabric-1.19.2-0.5.0.jar
├── Pehkui-3.6.3+1.14.4-1.19.3.jar
├── picturesign-1.4.1.jar
├── player-animation-lib-fabric-0.4.2.jar
├── playerex-3.5.1.jar
├── plushie-mod-1.2.jar
├── polaroidcamera-1.4.1.jar
├── PresenceFootsteps-1.6.4.jar
├── purpeille-3.2.3+fabric-1.19.jar
├── PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
├── qu-enchantments-1.2.4-1.19.jar
├── randomized_default_fireworks-1.0.0+1.19.jar
├── ratsmischief-1.4.0.jar
├── resourcefulconfig-fabric-1.19.2-1.0.18.jar
├── resourcefullib-fabric-1.19.2-1.1.19.jar
├── revelationary-1.2.0.jar
├── right-click-harvest-3.1.0+1.19-1.19.2.jar
├── RoughlyEnoughItems-9.1.585.jar
├── RoughlyEnoughLootTables-1.19-1.0.jar
├── RoughlyEnoughProfessions-fabric-1.19.2-1.1.3.jar
├── RoughlyEnoughTrades-1.19-1.0.jar
├── scout-1.19.2-1.1.2.jar
├── servercore-1.3.3-1.19.2.jar
├── server-hats-1.19-1.19.2-0.13.jar
├── simplechunkloader-1.0.2-1.19.jar
├── simplyswords-fabric-1.37-1.19.2.jar
├── smoothboot-fabric-1.19-1.7.1.jar
├── spawnermod-1.19.0-1.2.0+Fabric.jar
├── spectrum-1.6.5-1.19.2-leisure_time.jar
├── spirit-walker-0.1.1+1.19.jar
├── stormfest-v1.3.1.jar
├── symbol-chat-1.19.2-0.5.1.jar
├── terrestria-5.0.8.jar
├── things-0.3.0+1.19.jar
├── toms_storage_fabric-1.19-1.4.6.jar
├── toolleveling-fabric-1.19.2-1.4.1.jar
├── TooManyOrigins-0.7.0+1.19-fabric.jar
├── torohealth-1.19-fabric-1.jar
├── transparent-5.1.2+1.19-fabric.jar
├── trinkets-3.4.2.jar
├── twigs-2.0.0-beta.9+1.19-fabric.jar
├── visuality-0.5.5.jar
├── voicechat-fabric-1.19.2-2.3.27.jar
├── weirdchat-1.0.0.jar
├── whereisit-1.19.2-1.14.13.jar
├── WilderWild-1.1.8-Fabric+1.19.2.jar
├── windchimes-1.2.1.jar
├── wraith-alloy-forgery-2.0.17+1.19.jar
├── wthit-fabric-5.13.4.jar
├── YetAnotherConfigLib-2.2.0-for-1.19.2.jar
├── youre-in-grave-danger-1.4.8.jar
├── zenith-0.4.1+1.19.2.jar
└── Zoomify-2.9.0.jar

1 directory, 184 files

### Additional Information

I'm using prism launcher on arch linux.

**Comment by MBatt1** [comment]
Likely not an issue with latest version but closing due to being 16 months old.
