### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by bdashore3** [devs-immortal/The-Aether#76]
Logs: 
[latest.log](https://github.com/devs-immortal/The-Aether/files/5771465/latest.log)

Crash report: 
[crash-2021-01-05_11.43.50-client.txt](https://github.com/devs-immortal/The-Aether/files/5771476/crash-2021-01-05_11.43.50-client.txt)

**Comment by Kichura** [comment]
You must manually install Geckolib (for fabric) to play with the aether mod.

**Comment by bdashore3** [comment]
I did have geckolib installed in my production modpack, however it's 2.0.0 due to incompatibility with Ars Theurgia with 3.0.0

**Comment by bdashore3** [comment]
Update: Loads now with Geckolib 2.0 and 3.0 in the same instance. Closing this issue.
