### ISSUE TITLE
Dried Bamboo Mod Incompatibility

### ISSUE THREAD

**Issue by ereese99** [devs-immortal/The-Aether#764]
For some reason there's a crash with the Dried Bamboo mod on 1.19.2, crash report attached.
[crash-2023-02-17_08.32.35-client.txt](https://github.com/devs-immortal/Paradise-Lost/files/10767238/crash-2023-02-17_08.32.35-client.txt)

**Comment by MBatt1** [comment]
Should be fixed for minecraft versions 1.19.4 and higher
Please reopen an issue if it is not resolved.
