### ISSUE TITLE
Support for older Minecraft versions

### ISSUE THREAD

**Issue by Arr4y** [devs-immortal/The-Aether#770]
### Problem

There's lack of support for running newer versions of Paradise Lost on older versions of Minecraft.

### Suggestions (Optional)

Add newer versions of Paradise Lost for older Minecraft versions such as 1.18.2. This will help keep up to date with the mod as many other mods take a long time to transition to newer versions.

### Mod Version

Beta 2.1.0

**Comment by CDAGaming** [comment]
As much as we would love to support multiple versions of minecraft, our team is both limited in time and resources.
It also limits our capabilities if we have to design features that work consistently on multiple versions of the game,
rather then being able to iterate and improve our mod as the game's logic improves in newer versions of the game.

However, we can look at feedback and see whether or not (Once the core mod is stable) there is an audience for some older versions of the game.

**Comment by CDAGaming** [comment]
Leaving this open in case any of the other team members have thoughts.

**Comment by MBatt1** [comment]
Yeah, I am in agreement with CDA (unforunately). We simply don't have enough resources dedicated to this mod to keep it updated on multiple versions while still adding new content to the next version. This mod is listed as "IN BETA" and more now than ever is it true. We are still feeling out features for the mod and at this time we'd never get a new update out if we had to backport features to 1.18.x
