### ISSUE TITLE
Bug: ViveCraft compatibility

### ISSUE THREAD

**Issue by thefraiman** [devs-immortal/The-Aether#771]
### What happened?

When I enter a world wherever I am in the world my FPS is locked to a maximum of 18 frames, only if there is a modification of Lost Paradise, without this mod, the game through VR in 72 fps maximum for me.

To replicate:
1. Download my mods collection
2. Enter to the normal world, overworld via ViveCraft, VR helmet and controllers
3. Check the FPS for a few minutes

### Mod Version

beta 2.1.0

### Fabric API Version

0.76.0

### Relevant log output

```Shell
https://drive.google.com/file/d/11j2RI9pM_Zzaf--5p-xui8Ls7Pe7aurA/view?usp=sharing

(i cant paste, the limit of text)
```

### Other mods

https://drive.google.com/file/d/1pV4YxvGiYbfhtq-TYbC9K2q8N9q-49Ru/view?usp=sharing

### Additional Information

I found a temporary solution to this problem is to reduce the quality of the VR helmet screen resolution to 50%, but this is not what I would like to play with, and such a slump FPS causes Lost Paradise.

Also for incase, using multimc launcher

**Comment by MBatt1** [comment]
I'm unable to test this but I suspect it might be far improved on 2.2.x versions of PL. Please feel free to re-open the issue if FPS is not improved
