### ISSUE TITLE
Accessibility: 1.20?

### ISSUE THREAD

**Issue by SafeOfArsenal** [devs-immortal/The-Aether#774]
### Problem

i want to play this on 1.20 fabric

### Suggestions (Optional)

e

### Mod Version

e

### Additional Information

e

**Comment by Jack-Papel** [comment]
e

**Comment by Azzyypaaras** [comment]
e

**Comment by MBatt1** [comment]
e

**Comment by Flatkat** [comment]
Are we going to get 1.20?

**Comment by MBatt1** [comment]
In progress, update posted on Discord. Closing
