### ISSUE TITLE
Paradise Lost vs The Aether vs The Aether Reborn

### ISSUE THREAD

**Issue by allanonmage** [devs-immortal/The-Aether#776]
### Feature

I've never played the original The Aether mod, but I see that it's back.  I play on Fabric though, and they haven't implemented it in Fabric, nor committed to doing so.  I see that your mod stopped at 1.19.2

Are you ceasing development and ceding ground to The Aether, or will you be carrying on your work in parallel?  If the latter, do you plan to continue this mod into 1.20 and beyond?

Did this project change it's name from The Aether Reborn, or is that a different project?

### Mod Version

Fabric

**Comment by MBatt1** [comment]
This project was originally a port of the Aether to Fabric just called "The Aether", but when the original porters got into hot water with the real Aether team it got rebranded to "Aether Reborn". I joined this team about this time and it was meant to be a spinoff/alternate Aether 2 version with original Aether features but new content like how Aether 2 expanded the game. When Aether development on Forge continued back up they didn't like us using Aether assets so we fully pivoted away and changed again to "Paradise Lost".

This mod will continue to 1.20+ though
