### ISSUE TITLE
Bug: Can't activate portal frame

### ISSUE THREAD

**Issue by Zarvera** [devs-immortal/The-Aether#778]
### What happened?

For some reason, the portal is bot activating at all. That is, if it's supposed to be built same way Aether had it's portal built - a 5 tall 4 wide Glowstone block frame. Putting down water inside frame then does nothing.

![2023-11-05_17 52 41](https://github.com/devs-immortal/Paradise-Lost/assets/44240662/d212e3c4-4de9-4b14-aeda-e1b7e12635d6)

There's no crash and log has no relevant output.
Any ideas?

### Mod Version

2.1.0

### Fabric API Version

0.76.1

### Other mods

Advanced Tooltips
Paradise Lost
Amecs
Animatica
AppleSkin
Architect's Palette [Fabric]
Architectury API
AttributeFix
Aylyth
AzureLib
BCLib
Beacon Overhaul
Beneath the Wetlands
Better Combat
Better Jukebox
BetterEnd
Bits And Chisels
Bookshelf
Bosses of Mass Destruction
Botarium
Brainier Bees
Cardinal Components API
Catwalks Inc.
ChickensShed
ChoiceTheorem's Overhauled Village
Chunk Loaders
Cloth Config API
Collective
Connectible Chains [Fabric]
Continuity
Controlling
Convenient mobGriefing
Create Fabric
Create Utilities
Create: Extended Cogwheels
Create: Steam 'n' Rails
Dark Waters
Debugify
Deeper Dark
Deeper and Darker
Despawning Eggs Hatch
DimensionalDoors
Drip Sounds (Fabric)
Droplight
Dungeons and Taverns
EMI
EMI Addon: Extra Mod Integrations
EMI Loot
EMI Trades
EMICompat
EMIffect
EdenRing
Enchantment Descriptions
Entity Collision FPS Fix
Entity Culling
Equipment Compare
Excorrelation
Explorer's Compass
Explorify
Explosive Enhancement
Fabric API
Fabric Language Kotlin
Falling Leaves
Fast Backups
Fast Leaf Decay
FerriteCore
Forge Config API Port
Fusion (Connected Textures)
Geckolib
Gigeresque
Handcrafted
Harvest with ease
Hybrid Aquatic
Iceberg
Immersive Armors
Indium
Infinity Buttons
Inventory Tabs (updated)
Iris Flywheel Compat
Iris Shaders
LambDynamicLights
LazyDFU
Legendary Tooltips
Let Me Despawn
Liberty's Villagers
Lithium
MVS - Moog's Voyager Structures
Marium's Soulslike Weaponry
Memory Leak Fix
MidnightLib
Mine Cells - Dead Cells Mod
Mob Plaques
Mod Menu
ModernFix
Moonlight Lib
More Doors
Mouse Tweaks
Nature's Compass
Neruina - Ticking Entity Fixer
No Chat Reports
Nyctophobia
Nyctophobia Dread
Nyf's Spiders
Patchouli
Phosphor
Prism
Puzzles Lib
Reaper
Rechiseled
Rechiseled: Create
Regions Unexplored
Resourceful Lib
Revelationary
Sculk Expansion
Simply Swords
SmartBrainLib
Sodium
Sound Physics Remastered
Special Mobs
Spectrum
Spirit
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
TerraBlender
TerraMine
The Graveyard (FABRIC)
Tool Stats
ToolTipFix
Tree Harvester
Trinkets
Ultris: Boss Expansion
Upgraded Mobs
Visual Overhaul
Visuality
Vitalize
WTHIT
Wormhole (Portals)
Xaero's Minimap
Xaero's World Map
YUNG's API
YUNG's Better Ocean Monuments
YetAnotherConfigLib
You're in Grave Danger
Yttr
Zoomify
bad packets
megane
oωo (owo-lib)
playerAnimator

**Comment by MBatt1** [comment]
Fixed in 2.2.1 with inclusion of correct portal api version.
