### ISSUE TITLE
Bug: portal malfunction

### ISSUE THREAD

**Issue by Renderingforest** [devs-immortal/The-Aether#781]
### What happened?

When creating the portal the middle effects were red and when going through it took me to the nether above the obsidian level.

### Mod Version

1.19.2

**Comment by Micaxs** [comment]
This happens on Medieval MC v24 as well. 
Creating a portal in the overworld brings you to the nether roof.

Fabric Loader:  0.14.24
Mod version: paradise-lost-2.1.0-beta+1.19.2.jar
Other mods: Medieval MC 1.19.2 v24 Modpack.

**Comment by EratoTiaTuatha** [comment]
Same issue, MC19.2 inside the Better Minecraft v20 modpack. Was fine on Better Minecraft 19.5, so I'm guessing the Paradise Lost mod was updated in the modpack update.

**Comment by MBatt1** [comment]
Please download this version of the portal API and drop it into your mods folder, this should resolve the problem:
https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/0.0.1-beta63.5-1.19.X/customportalapi-0.0.1-beta63.5-1.19.X.jar

**Comment by Desno05** [comment]
same issue with v20.i place the water bucket but it became a red portal that takes me on the roof of the nether

**Comment by thegaycarrot** [comment]
> Please download this version of the portal API and drop it into your mods folder, this should resolve the problem: https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/0.0.1-beta63.5-1.19.X/customportalapi-0.0.1-beta63.5-1.19.X.jar

I added this and it still is not working for better minecraft v20
