### ISSUE TITLE
(1.19.2) Mod's chests textures go missing during minecraft Christmas / New Year event

### ISSUE THREAD

**Issue by Unshoshable** [devs-immortal/The-Aether#782]
### What happened?

These textures are completely fine every other time, except when humanity approaches Christmas / New year events. Also, for whatever reason, among all mods that add new chests, only the ones from Paradise Lost lose their appearance. That means these chests are fine until 20th of december and after the holidays' retreat (or smth like that, I don't remember when specifically).
![image_2023-12-26_14-51-24](https://github.com/devs-immortal/Paradise-Lost/assets/149245115/6754260d-e828-45da-b364-371720980cb0)
![image_2023-12-26_14-52-33](https://github.com/devs-immortal/Paradise-Lost/assets/149245115/aa5ad3b5-b0d9-480b-9ba5-2f1b67e40626)

### Mod Version

Beta 2.1.0

### Fabric API Version

0.76.1

### Relevant log output

```Shell
Does not cause a crash
```

### Other mods

It appears other mods don't matter, the issue is localized within described conditions

### Additional Information

I am using Prism Launcher 8.0

**Comment by MBatt1** [comment]
Oh good to know- we never made christmas textures for the chests, that's why :)

**Comment by Aethyus** [comment]
Ehh actually, adding Christmas variants of some textures would be fun!
