### ISSUE TITLE
Bug:  Missing items and ores

### ISSUE THREAD

**Issue by Vector280** [devs-immortal/The-Aether#804]
### What happened?

A bug happened!

To replicate:
1. First, I tried to enter the portal in the modpack "Better minecraft 1.19.2", and there was no mob or entity
2. Next, I tried to mine to find ores, after a couple minutes i search in the REI mod just to find out there was no ores
3. Finally, I exit the portal, restart but nothing 
![Captura de pantalla 2024-06-18 210833](https://github.com/devs-immortal/Paradise-Lost/assets/173224548/6f01cebd-bac0-4a9d-b013-b40eb9026c1b)
![Captura de pantalla 2024-06-18 211322](https://github.com/devs-immortal/Paradise-Lost/assets/173224548/c764a8fa-da4c-445a-bfee-19936009632b)

### Mod Version

v2.1.0-beta+1.19.2

### Fabric API Version

1.19.2

### Other mods

![Captura de pantalla 2024-06-18 211642](https://github.com/devs-immortal/Paradise-Lost/assets/173224548/405e9c80-09fd-48e4-8d2e-eeeffe8fba7f)

### Additional Information

at first I couldnt even enter the Paradise with a Portal until I use this mod 
![image](https://github.com/devs-immortal/Paradise-Lost/assets/173224548/c8c25734-1814-45ae-a9bb-097f077575b3)

**Comment by MBatt1** [comment]
They are using an old version of Paradise Lost. If you can manually update the mod to 2.2.1 (1.19.2) it should fix the portal issue at least, but I've never seen blocks and items be missing

**Comment by MBatt1** [comment]
Please see my fix described above, if the issue persists feel free to reopen this ticket.
