### ISSUE TITLE
Bug: Portal Doesn't generate when making the portal and lighting it with latest version on 1.20.1

### ISSUE THREAD

**Issue by TheShadyyOneYT** [devs-immortal/The-Aether#806]
### What happened?

portal doesn’t generate when placing water to enter the lost paradise dimension. The blue portals don’t form like the nether does with obsidian and flint & Steel.

To replicate:
1. First, download the latest beta for fabric 1.20.1
2. Next, open the game and try to construct a portal like you would with the aether (if that's how you enter)
3. Finally, portal doesn't work. It won't generate the portal. It simply just continues to flow with water

### Mod Version

Beta 2.2.1

### Fabric API Version

0.92.2

### Relevant log output

```Shell
My log is too big unfortunately to show it, if there is a 
specific thing you are looking for within it let me know. 
I will gladly show you if absolutely necessary.
```

### Other mods

Modlist:
![Screenshot 2024-08-18 231943](https://github.com/user-attachments/assets/263fcdf4-558d-4edc-80ee-fe64b169f174)
![Screenshot 2024-08-18 231958](https://github.com/user-attachments/assets/605ddfe0-ca5a-4019-8797-886c97cac984)
![Screenshot 2024-08-18 232013](https://github.com/user-attachments/assets/3d9b1b26-9026-4ab1-ad5d-f2f587963159)
![Screenshot 2024-08-18 232020](https://github.com/user-attachments/assets/659f1e5f-07ec-4650-9b4d-8532406aa31e)

### Additional Information

Nope, just the portal simply won't work. The only way to currently access it is via commands with `/setblock paradise_lost:blue_portal ~ ~ ~`

![2024-08-19_00 32 55](https://github.com/user-attachments/assets/e615403e-e714-4632-81e8-021ce40a661b)

**Comment by unilock** [comment]
The portal frame is made of Bloomed Calcite now. You get it by applying (right-clicking) a Potion of Healing to regular Calcite blocks in-world.

**Comment by MBatt1** [comment]
Yes, the portal frame is made with Bloomed Calcite and not glowstone as to not conflict with the Aether.
You can right click a regular potion onto a calcite block, or use a splash/lingering potion onto calcite blocks to get 2 bloomed calcite per potion. 

Since this is how it is shown in preview screenshots and how it is explained in the advancements I will be closing this issue

**Comment by TheShadyyOneYT** [comment]
Thank you
