### ISSUE TITLE
Feature: Allays in Paradise Lost

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [devs-immortal/The-Aether#813]
### Feature

making allays spawn in paradise lost naturally. Expansion to this idea: vexes in the nether, allays can have villages to spawn in and gain the ability to open doors. the allays could have an aether counterpart and turn into traditional allays upon leaving the aether i.e. piglins. vexes could also have a nether counterpart.

**Comment by MBatt1** [comment]
I think that Overworld/vanilla mobs should be separated from Paradise in a similar way that the Nether is and having natural Allays kinda ruins the unique way that they are normally obtained. Possibly there could be some interaction with overworld mobs but they shouldn't spawn in my opinion. Sorry!

This would be trivial to add through a datapack though if you are interested in that you could add both vexes to the Nether and allays to Paradise to use in your own worlds/modpack
