### ISSUE TITLE
Bug: portal not working

### ISSUE THREAD

**Issue by natxukii** [devs-immortal/The-Aether#816]
### What happened?

Bug for the aether portal 
please help!
To replicate:
creating the portal it turns red and teleports me to the roof of the nether, i found some links online to download this https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/0.0.1-beta63.5-1.19.X/customportalapi-0.0.1-beta63.5-1.19.X.jar and it only makes the portal blue and adds the sounds, it still brings me to the roof of the nether

### Mod Version

Beta 2.1.0

### Fabric API Version

0.14.24

### Other mods

I use better MC fabric BMC1 1.19.2 v20 

![Screenshot 2024-09-29 175818](https://github.com/user-attachments/assets/6562071f-0074-4838-b88b-d02cdb6eeca8)

**Comment by MBatt1** [comment]
Did you rebuild the portal after adding the customportalapi jar? You may need to break the portal and remake it after that mod is installed. 

If this does not fix it, please manually update PL to 2.2.1 which you can get from here, and remove the customportalapi jar
https://github.com/devs-immortal/Paradise-Lost/releases/tag/b2.2.1

**Comment by natxukii** [comment]
> Did you rebuild the portal after adding the customportalapi jar? You may need to break the portal and remake it after that mod is installed.
> 
> If this does not fix it, please manually update PL to 2.2.1 which you can get from here, and remove the customportalapi jar https://github.com/devs-immortal/Paradise-Lost/releases/tag/b2.2.1

I did rebuild the portal and it still didn't work, i downloaded the new release and removed the old version and the customportalapi and now its just red and doesnt work lol, i even made a new world and everything
![Screenshot 2024-09-29 182223](https://github.com/user-attachments/assets/e94e2922-2105-4a25-b62c-352225937eb8)

**Comment by MBatt1** [comment]
you'll need to build to portal out of a new material "bloomed calcite" does that work

**Comment by dijana04** [comment]
i have the same problem and i have no idea how to fix it

**Comment by MBatt1** [comment]
@dijana04 what version are you on? Minecraft version and Paradise Lost Version

**Comment by MBatt1** [comment]
I'll be closing this, please open a ticket if you have already updated to the latest version and tried building the portal out of bloomed calcite
