### ISSUE TITLE
Question about Translation for "Puffin" in crowdin

### ISSUE THREAD

**Issue by someone5678** [devs-immortal/The-Aether#82]
In crowdin, Context on "block.the_aether.aether_bush" - as "Puffin", a type of bird.

Is this a newly added mob in The Aether Reborn?
Or wrongly connected context?

**Comment by Dragonoidzero** [comment]
No, it is a bush named after the bird.

**Comment by someone5678** [comment]
> No, it is a bush named after the bird.

Thanks for confirming!
