### ISSUE TITLE
Aether Grass Block has grey top in hand model

### ISSUE THREAD

**Issue by MBatt1** [devs-immortal/The-Aether#89]
![image](https://user-images.githubusercontent.com/53229958/106397864-4151dd00-63d5-11eb-87e5-084530e3c11d.png)
![image](https://user-images.githubusercontent.com/53229958/106397867-4878eb00-63d5-11eb-9371-718c8273e5c6.png)

**Comment by CDAGaming** [comment]
Closed in favor of #147
